; ModuleID = 'e01'
source_filename = "e01"

@x = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  %x = load i64, i64* @x
  %0 = icmp eq i64 %x, 1
  br i1 %0, label %then, label %else

then:                                             ; preds = %entry
  store i64 0, i64* @x
  br label %ifcont

else:                                             ; preds = %entry
  store i64 2, i64* @x
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %x1 = load i64, i64* @x
  ret i64 %x1
}
