; ModuleID = 'e02'
source_filename = "e02"

@x = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  %x = load i64, i64* @x
  %0 = icmp eq i64 %x, 0
  %x1 = load i64, i64* @x
  %1 = icmp eq i64 %x1, 7
  %subtmp = or i1 %0, %1
  br i1 %subtmp, label %then, label %else

then:                                             ; preds = %entry
  store i64 77, i64* @x
  br label %ifcont

else:                                             ; preds = %entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %x2 = load i64, i64* @x
  ret i64 %x2
}
