; ModuleID = 'e04'
source_filename = "e04"

@e04_x = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  store i64 2, i64* @e04_x
  %x = load i64, i64* @e04_x
  %0 = icmp eq i64 %x, 1
  br i1 %0, label %then, label %elsif0

then:                                             ; preds = %entry
  store i64 10, i64* @e04_x
  br label %ifcont

elsif0:                                           ; preds = %entry
  %x1 = load i64, i64* @e04_x
  %1 = icmp eq i64 %x1, 2
  br i1 %1, label %then2, label %elsif1

then2:                                            ; preds = %elsif0
  store i64 20, i64* @e04_x
  br label %ifcont

elsif1:                                           ; preds = %elsif0
  %x3 = load i64, i64* @e04_x
  %2 = icmp eq i64 %x3, 3
  br i1 %2, label %then4, label %else

then4:                                            ; preds = %elsif1
  store i64 30, i64* @e04_x
  br label %ifcont

else:                                             ; preds = %elsif1
  store i64 90, i64* @e04_x
  br label %ifcont

ifcont:                                           ; preds = %else, %then4, %then2, %then
  %x5 = load i64, i64* @e04_x
  ret i64 %x5
}
