; ModuleID = 'e10'
source_filename = "e10"

@e10_x = internal global i64 0
@e10_y = internal global i64 0

define i64 @output() {
entry:
  store i64 0, i64* @e10_x
  br label %while

while:                                            ; preds = %end, %entry
  %x = load i64, i64* @e10_x
  %0 = icmp sle i64 %x, 100
  br i1 %0, label %loop, label %end6

loop:                                             ; preds = %while
  store i64 0, i64* @e10_y
  br label %while1

while1:                                           ; preds = %loop2, %loop
  %y = load i64, i64* @e10_y
  %1 = icmp slt i64 %y, 10
  br i1 %1, label %loop2, label %end

loop2:                                            ; preds = %while1
  %x3 = load i64, i64* @e10_x
  %addtmp = add i64 %x3, 1
  store i64 %addtmp, i64* @e10_x
  %y4 = load i64, i64* @e10_y
  %addtmp5 = add i64 %y4, 1
  store i64 %addtmp5, i64* @e10_y
  br label %while1

end:                                              ; preds = %while1
  br label %while

end6:                                             ; preds = %while
  %x7 = load i64, i64* @e10_x
  ret i64 %x7
}
