; ModuleID = 'f02'
source_filename = "f02"

@f02_i = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @output() {
entry:
  %i = alloca i64
  store i64 1, i64* %i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %i1 = load i64, i64* %i
  call void @WriteInt(i64 %i1)
  call void @WriteLn()
  %0 = load i64, i64* %i
  %nextvar = add i64 %0, 1
  store i64 %nextvar, i64* %i
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 12
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond2 = icmp sge i64 %nextvar, 12
  br i1 %loopcond2, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  ret i64 0
}
