; ModuleID = 'f03'
source_filename = "f03"

@f03_i = internal global i64 0

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  %i = alloca i64
  store i64 1, i64* %i
  br label %loop

loop:                                             ; preds = %loop, %entry
  %i1 = load i64, i64* %i
  %modtmp = srem i64 %i1, 2
  %0 = icmp eq i64 %modtmp, 0
  call void @WriteBoolean(i1 %0)
  call void @WriteLn()
  %1 = load i64, i64* %i
  %nextvar = add i64 %1, 1
  store i64 %nextvar, i64* %i
  %loopcond = icmp sle i64 %nextvar, 12
  br i1 %loopcond, label %loop, label %afterloop

afterloop:                                        ; preds = %loop
  ret i64 0
}
