; ModuleID = 'g01'
source_filename = "g01"

@x1 = internal global i64 0
@x2 = internal global [5 x i64] zeroinitializer
@x3 = internal global [6 x i1] zeroinitializer

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define void @f() {
entry:
  %z3 = alloca [6 x i1]
  %z2 = alloca [4 x i64]
  %z1 = alloca i64
  store i64 0, i64* %z1
  store [4 x i64] zeroinitializer, [4 x i64]* %z2
  store [6 x i1] zeroinitializer, [6 x i1]* %z3
  ret void
}

define i64 @output() {
entry:
  call void @f()
  ret i64 0
}
