; ModuleID = 'g04'
source_filename = "g04"

@g04_x = internal global [3 x i1] zeroinitializer
@g04_i = internal global i64 0

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  store i1 false, i1* getelementptr inbounds ([3 x i1], [3 x i1]* @g04_x, i64 0, i64 0)
  store i1 true, i1* getelementptr inbounds ([3 x i1], [3 x i1]* @g04_x, i64 0, i64 1)
  store i1 false, i1* getelementptr inbounds ([3 x i1], [3 x i1]* @g04_x, i64 0, i64 2)
  store i64 0, i64* @g04_i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %x = load [3 x i1], [3 x i1]* @g04_x
  %i = load i64, i64* @g04_i
  %idx = getelementptr [3 x i1], [3 x i1]* @g04_x, i64 0, i64 %i
  %idx1 = load i1, i1* %idx
  call void @WriteBoolean(i1 %idx1)
  call void @WriteLn()
  %index = load i64, i64* @g04_i
  %nextvar = add i64 %index, 1
  store i64 %nextvar, i64* @g04_i
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 2
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond2 = icmp sge i64 %nextvar, 2
  br i1 %loopcond2, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  %x3 = load [3 x i1], [3 x i1]* @g04_x
  %idx4 = load i1, i1* getelementptr inbounds ([3 x i1], [3 x i1]* @g04_x, i64 0, i64 0)
  br i1 %idx4, label %or_end, label %or_next

or_next:                                          ; preds = %afterloop
  %x5 = load [3 x i1], [3 x i1]* @g04_x
  %idx6 = load i1, i1* getelementptr inbounds ([3 x i1], [3 x i1]* @g04_x, i64 0, i64 1)
  br i1 %idx6, label %or_end, label %or_next7

or_next7:                                         ; preds = %or_next
  %x8 = load [3 x i1], [3 x i1]* @g04_x
  %idx9 = load i1, i1* getelementptr inbounds ([3 x i1], [3 x i1]* @g04_x, i64 0, i64 2)
  br label %or_end

or_end:                                           ; preds = %or_next7, %or_next, %afterloop
  %or = phi i1 [ %idx4, %afterloop ], [ %idx6, %or_next ], [ %idx9, %or_next7 ]
  %0 = zext i1 %or to i64
  ret i64 %0
}
