; ModuleID = 'g07'
source_filename = "g07"

%0 = type { i64, i64, i64 }
%1 = type { i64, i64, i64 }

@g07_pt = internal global %0 zeroinitializer

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  store i64 3, i64* getelementptr inbounds (%0, %0* @g07_pt, i64 0, i32 0)
  store i64 2, i64* getelementptr inbounds (%0, %0* @g07_pt, i64 0, i32 1)
  store i64 5, i64* getelementptr inbounds (%0, %0* @g07_pt, i64 0, i32 2)
  %pt = load %0, %0* @g07_pt
  %idx = load i64, i64* getelementptr inbounds (%0, %0* @g07_pt, i64 0, i32 0)
  %pt1 = load %0, %0* @g07_pt
  %idx2 = load i64, i64* getelementptr inbounds (%0, %0* @g07_pt, i64 0, i32 1)
  %addtmp = add i64 %idx, %idx2
  %pt3 = load %0, %0* @g07_pt
  %idx4 = load i64, i64* getelementptr inbounds (%0, %0* @g07_pt, i64 0, i32 2)
  %addtmp5 = add i64 %addtmp, %idx4
  ret i64 %addtmp5
}
