; ModuleID = 'g11'
source_filename = "g11"

@g11_pt = internal global [3 x i64] zeroinitializer
@g11_i = internal global i64 0

define internal [3 x i64] @g11_identity([3 x i64] %a) {
entry:
  %a1 = alloca [3 x i64]
  store [3 x i64] %a, [3 x i64]* %a1
  %a2 = load [3 x i64], [3 x i64]* %a1
  ret [3 x i64] %a2
}

define internal i64 @g11_sum([3 x i64] %a) {
entry:
  %i = alloca i64
  %total = alloca i64
  %a1 = alloca [3 x i64]
  store [3 x i64] %a, [3 x i64]* %a1
  store i64 0, i64* %total
  store i64 0, i64* %i
  store i64 0, i64* %i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %total2 = load i64, i64* %total
  %a3 = load [3 x i64], [3 x i64]* %a1
  %i4 = load i64, i64* %i
  %idx = getelementptr [3 x i64], [3 x i64]* %a1, i64 0, i64 %i4
  %idx5 = load i64, i64* %idx
  %addtmp = add i64 %total2, %idx5
  store i64 %addtmp, i64* %total
  %index = load i64, i64* %i
  %nextvar = add i64 %index, 1
  store i64 %nextvar, i64* %i
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 2
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond6 = icmp sge i64 %nextvar, 2
  br i1 %loopcond6, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  %total7 = load i64, i64* %total
  ret i64 %total7
}

define i64 @output() {
entry:
  store i64 0, i64* @g11_i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %i = load i64, i64* @g11_i
  %i1 = load i64, i64* @g11_i
  %multmp = mul i64 %i, %i1
  %i2 = load i64, i64* @g11_i
  %addtmp = add i64 %multmp, %i2
  %addtmp3 = add i64 %addtmp, 1
  %i4 = load i64, i64* @g11_i
  %idx = getelementptr [3 x i64], [3 x i64]* @g11_pt, i64 0, i64 %i4
  store i64 %addtmp3, i64* %idx
  %index = load i64, i64* @g11_i
  %nextvar = add i64 %index, 1
  store i64 %nextvar, i64* @g11_i
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 2
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond5 = icmp sge i64 %nextvar, 2
  br i1 %loopcond5, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  %pt = load [3 x i64], [3 x i64]* @g11_pt
  %0 = call [3 x i64] @g11_identity([3 x i64] %pt)
  %1 = call i64 @g11_sum([3 x i64] %0)
  ret i64 %1
}
