; ModuleID = 'record13'
source_filename = "record13"

%List = type { i64, i64 }

@record13_current = internal global %List zeroinitializer

define i64 @output() {
entry:
  store i64 5, i64* getelementptr inbounds (%List, %List* @record13_current, i64 0, i32 0)
  %current = load %List, %List* @record13_current
  %idx = load i64, i64* getelementptr inbounds (%List, %List* @record13_current, i64 0, i32 0)
  ret i64 %idx
}
