; ModuleID = 'c05'
source_filename = "c05"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@alpha = internal constant i64 24
@x = internal global i64 0
@y = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @output() {
entry:
  %x = load i64, i64* @x
  %alpha = load i64, i64* @alpha
  %subtmp = sub i64 %x, %alpha
  ret i64 %subtmp
}
