; ModuleID = 'c06'
source_filename = "c06"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

define i64 @output() {
entry:
  %y = alloca i64
  %x = alloca i64
  %alpha = alloca i64
  store i64 24, i64* %alpha
  store i64 0, i64* %x
  store i64 0, i64* %y
  store i64 3, i64* %x
  %x1 = load i64, i64* %x
  %addtmp = add i64 %x1, 987
  store i64 %addtmp, i64* %y
  %y2 = load i64, i64* %y
  ret i64 %y2
}
