; ModuleID = 'c06'
source_filename = "c06"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@alpha = internal constant i64 24
@x = internal global i64 0
@y = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @output() {
entry:
  store i64 3, i64* @x
  %x = load i64, i64* @x
  %addtmp = add i64 %x, 987
  store i64 %addtmp, i64* @y
  %y = load i64, i64* @y
  ret i64 %y
}
