; ModuleID = 'd04'
source_filename = "d04"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@y = internal constant i64 3

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @f() {
entry:
  %y = alloca i64
  store i64 4, i64* %y
  %y1 = load i64, i64* %y
  ret i64 %y1
}

define i64 @output() {
entry:
  %y = load i64, i64* @y
  ret i64 %y
}
