; ModuleID = 'd08'
source_filename = "d08"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@y = internal global i64 0

define i64 @f() {
entry:
  %yy = alloca i64
  store i64 0, i64* %yy
  %yy1 = load i64, i64* %yy
  %addtmp = add i64 %yy1, 2
  ret i64 %addtmp
}

define i64 @output() {
entry:
  %calltmp = call i64 @f()
  %addtmp = add i64 5, %calltmp
  %calltmp1 = call i64 @f()
  %calltmp2 = call i64 @f()
  %multmp = mul i64 %calltmp1, %calltmp2
  %addtmp3 = add i64 %addtmp, %multmp
  ret i64 %addtmp3
}

; Function Attrs: nounwind
declare void @llvm.stackprotector(i8*, i8**) #0

attributes #0 = { nounwind }
