; ModuleID = 'd09'
source_filename = "d09"

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @f(i64 %x) {
entry:
  %x1 = alloca i64
  store i64 %x, i64* %x1
  %x2 = load i64, i64* %x1
  %addtmp = add i64 %x2, 2
  ret i64 %addtmp
}

define i64 @output() {
entry:
  %calltmp = call i64 @f(i64 2)
  %addtmp = add i64 5, %calltmp
  %calltmp1 = call i64 @f(i64 3)
  %calltmp2 = call i64 @f(i64 4)
  %multmp = mul i64 %calltmp1, %calltmp2
  %addtmp3 = add i64 %addtmp, %multmp
  ret i64 %addtmp3
}
