; ModuleID = 'e08'
source_filename = "e08"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@x = internal global i64 0

define i64 @output() {
entry:
  store i64 0, i64* @x
  %x = load i64, i64* @x
  %addtmp = add i64 %x, 1
  store i64 %addtmp, i64* @x
  %x1 = load i64, i64* @x
  %addtmp2 = add i64 %x1, 1
  store i64 %addtmp2, i64* @x
  %x3 = load i64, i64* @x
  %addtmp4 = add i64 %x3, 1
  store i64 %addtmp4, i64* @x
  %x5 = load i64, i64* @x
  ret i64 %x5
}
