; ModuleID = 'e11'
source_filename = "e11"

@x = internal global i64 0
@y = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @output() {
entry:
  store i64 0, i64* @x
  br label %repeat

repeat:                                           ; preds = %end, %entry
  store i64 0, i64* @y
  br label %repeat1

repeat1:                                          ; preds = %repeat1, %repeat
  %x = load i64, i64* @x
  %addtmp = add i64 %x, 1
  store i64 %addtmp, i64* @x
  %y = load i64, i64* @y
  %addtmp2 = add i64 %y, 1
  store i64 %addtmp2, i64* @y
  %y3 = load i64, i64* @y
  %0 = icmp sgt i64 %y3, 9
  br i1 %0, label %end, label %repeat1

end:                                              ; preds = %repeat1
  %x4 = load i64, i64* @x
  %1 = icmp sgt i64 %x4, 100
  br i1 %1, label %end5, label %repeat

end5:                                             ; preds = %end
  %x6 = load i64, i64* @x
  ret i64 %x6
}
