; ModuleID = 'f01'
source_filename = "f01"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@x = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteLn()

define i64 @output() {
entry:
  store i64 12, i64* @x
  %x = load i64, i64* @x
  %calltmp = call void @WriteInt(i64 %x)
  %calltmp1 = call void @WriteLn()
  ret i64 0
}

; Function Attrs: nounwind
declare void @llvm.stackprotector(i8*, i8**) #0

attributes #0 = { nounwind }
