; ModuleID = 'g01'
source_filename = "g01"
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin18.7.0"

@x1 = internal global i64 0
@x2 = internal global [5 x i64] zeroinitializer
@x3 = internal global [6 x i1] zeroinitializer

declare void @WriteInt(i64)

declare void @WriteLn()

define void @f() {
entry:
  %z3 = alloca [6 x i1]
  %z2 = alloca [4 x i64]
  %z1 = alloca i64
  store i64 0, i64* %z1
  store [4 x i64] zeroinitializer, [4 x i64]* %z2
  store [6 x i1] zeroinitializer, [6 x i1]* %z3
  ret void
}

define i64 @output() {
entry:
  %calltmp = call void @f()
  ret i64 0
}

; Function Attrs: nounwind
declare void @llvm.stackprotector(i8*, i8**) #0

attributes #0 = { nounwind }
