; ModuleID = 'c07'
source_filename = "c07"

@c07_alpha = internal constant i64 24
@c07_x = internal global i64 0
@c07_y = internal global i1 false

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  store i1 false, i1* @c07_y
  %alpha = load i64, i64* @c07_alpha
  %multmp = mul i64 3, %alpha
  store i64 %multmp, i64* @c07_x
  %x = load i64, i64* @c07_x
  %0 = icmp eq i64 %x, 72
  %1 = xor i1 %0, true
  %2 = zext i1 %1 to i64
  ret i64 %2
}
