; ModuleID = 'd05'
source_filename = "d05"

@y = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @f() {
entry:
  %yy = alloca i64
  store i64 0, i64* %yy
  %yy1 = load i64, i64* %yy
  %addtmp = add i64 %yy1, 2
  ret i64 %addtmp
}

define i64 @output() {
entry:
  %y = load i64, i64* @y
  %addtmp = add i64 %y, 63
  ret i64 %addtmp
}
