; ModuleID = 'd07'
source_filename = "d07"

@d07_y = internal global i64 0

define internal i64 @d07_f() {
entry:
  %yy = alloca i64
  store i64 0, i64* %yy
  %yy1 = load i64, i64* %yy
  %addtmp = add i64 %yy1, 2
  ret i64 %addtmp
}

define i64 @output() {
entry:
  %0 = call i64 @d07_f()
  %addtmp = add i64 5, %0
  %1 = call i64 @d07_f()
  %2 = call i64 @d07_f()
  %multmp = mul i64 %1, %2
  %addtmp1 = add i64 %addtmp, %multmp
  ret i64 %addtmp1
}
