; ModuleID = 'd07'
source_filename = "d07"

@y = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @f() {
entry:
  %yy = alloca i64
  store i64 0, i64* %yy
  %yy1 = load i64, i64* %yy
  %addtmp = add i64 %yy1, 2
  ret i64 %addtmp
}

define i64 @output() {
entry:
  %calltmp = call i64 @f()
  %addtmp = add i64 5, %calltmp
  %calltmp1 = call i64 @f()
  %calltmp2 = call i64 @f()
  %multmp = mul i64 %calltmp1, %calltmp2
  %addtmp3 = add i64 %addtmp, %multmp
  ret i64 %addtmp3
}
