; ModuleID = 'd09'
source_filename = "d09"

define internal i64 @d09_f(i64 %x1) {
entry:
  %x = alloca i64
  store i64 %x1, i64* %x
  %x2 = load i64, i64* %x
  %addtmp = add i64 %x2, 2
  ret i64 %addtmp
}

define i64 @output() {
entry:
  %0 = call i64 @d09_f(i64 2)
  %addtmp = add i64 5, %0
  %1 = call i64 @d09_f(i64 3)
  %2 = call i64 @d09_f(i64 4)
  %multmp = mul i64 %1, %2
  %addtmp1 = add i64 %addtmp, %multmp
  ret i64 %addtmp1
}
