; ModuleID = 'd10'
source_filename = "d10"

define internal i64 @d10_add(i64 %x1, i64 %y2) {
entry:
  %y = alloca i64
  %x = alloca i64
  store i64 %x1, i64* %x
  store i64 %y2, i64* %y
  %x3 = load i64, i64* %x
  %y4 = load i64, i64* %y
  %addtmp = add i64 %x3, %y4
  ret i64 %addtmp
}

define internal i64 @d10_mult(i64 %x1, i64 %y2) {
entry:
  %y = alloca i64
  %x = alloca i64
  store i64 %x1, i64* %x
  store i64 %y2, i64* %y
  %x3 = load i64, i64* %x
  %y4 = load i64, i64* %y
  %multmp = mul i64 %x3, %y4
  ret i64 %multmp
}

define i64 @output() {
entry:
  %0 = call i64 @d10_mult(i64 3, i64 3)
  %1 = call i64 @d10_mult(i64 4, i64 4)
  %2 = call i64 @d10_add(i64 %0, i64 %1)
  ret i64 %2
}
