; ModuleID = 'char4'
source_filename = "char4"

@char4_x = internal global [3 x i32] zeroinitializer

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  store i32 958, i32* getelementptr inbounds ([3 x i32], [3 x i32]* @char4_x, i64 0, i64 0)
  store i32 22235, i32* getelementptr inbounds ([3 x i32], [3 x i32]* @char4_x, i64 0, i64 1)
  store i32 128126, i32* getelementptr inbounds ([3 x i32], [3 x i32]* @char4_x, i64 0, i64 2)
  %x = load [3 x i32], [3 x i32]* @char4_x
  %idx = load i32, i32* getelementptr inbounds ([3 x i32], [3 x i32]* @char4_x, i64 0, i64 2)
  %0 = zext i32 %idx to i64
  ret i64 %0
}
