; ModuleID = 'chr2'
source_filename = "chr2"

@chr2_x = internal global i64 0

declare i32 @CHR(i64)

declare i64 @ORD(i32)

declare void @Out_Char(i32)

declare void @Out_Ln()

define i64 @output() {
entry:
  %i = alloca i64
  %0 = call i64 @ORD(i32 128126)
  store i64 %0, i64* %i
  br label %loop

loop:                                             ; preds = %loop, %entry
  %i1 = load i64, i64* %i
  %1 = call i32 @CHR(i64 %i1)
  call void @Out_Char(i32 %1)
  call void @Out_Char(i32 32)
  %2 = load i64, i64* %i
  %nextvar = add i64 %2, 1
  store i64 %nextvar, i64* %i
  %3 = call i64 @ORD(i32 128126)
  %addtmp = add i64 %3, 9
  %loopcond = icmp sle i64 %nextvar, %addtmp
  br i1 %loopcond, label %loop, label %afterloop

afterloop:                                        ; preds = %loop
  call void @Out_Ln()
  ret i64 0
}
