; ModuleID = 'array3'
source_filename = "array3"

@array3_x = internal global [0 x i64] zeroinitializer
@array3_sum = internal global i64 0

declare void @Out_Ln()

declare void @Out_Int(i64)

declare void @Out_Char(i32)

define i64 @output() {
entry:
  %i8 = alloca i64
  %i = alloca i64
  %0 = call i64 @NEW_Array([0 x i64]* @array3_x, i64 80)
  store i64 0, i64* %i
  br label %loop

loop:                                             ; preds = %loop, %entry
  %i1 = load i64, i64* %i
  %i2 = load i64, i64* %i
  %multmp = mul i64 %i1, %i2
  %i3 = load i64, i64* %i
  %addtmp = add i64 %multmp, %i3
  %addtmp4 = add i64 %addtmp, 1
  %i5 = load i64, i64* %i
  %idx = getelementptr [0 x i64], [0 x i64]* @array3_x, i64 0, i64 %i5
  store i64 %addtmp4, i64* %idx
  %1 = load i64, i64* %i
  %nextvar = add i64 %1, 1
  store i64 %nextvar, i64* %i
  %loopcond = icmp sle i64 %nextvar, 9
  br i1 %loopcond, label %loop, label %afterloop

afterloop:                                        ; preds = %loop
  store i64 0, i64* %i8
  br label %loop6

loop6:                                            ; preds = %loop6, %afterloop
  %x = load [0 x i64], [0 x i64]* @array3_x
  %i9 = load i64, i64* %i8
  %idx10 = getelementptr [0 x i64], [0 x i64]* @array3_x, i64 0, i64 %i9
  %idx11 = load i64, i64* %idx10
  call void @Out_Int(i64 %idx11)
  call void @Out_Char(i32 32)
  %2 = load i64, i64* %i8
  %nextvar12 = add i64 %2, 1
  store i64 %nextvar12, i64* %i8
  %loopcond13 = icmp sle i64 %nextvar12, 9
  br i1 %loopcond13, label %loop6, label %afterloop7

afterloop7:                                       ; preds = %loop6
  call void @Out_Ln()
  ret i64 0
}

declare i64 @NEW_Array([0 x i64]*, i64)
