; ModuleID = 'case4'
source_filename = "case4"

@case4_c = internal global i32 0
@STRING_0 = private global [0 x i32] [i32 65, i32 0]
@STRING_1 = private global [0 x i32] [i32 66, i32 44, i32 67, i32 0]
@STRING_2 = private global [0 x i32] [i32 68, i32 45, i32 90, i32 0]

declare i32 @CHR(i64)

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define i64 @output() {
entry:
  %i = alloca i64
  store i64 1, i64* %i
  br label %loop

loop:                                             ; preds = %case_end, %entry
  %i1 = load i64, i64* %i
  %addtmp = add i64 64, %i1
  %0 = call i32 @CHR(i64 %addtmp)
  store i32 %0, i32* @case4_c
  %c = load i32, i32* @case4_c
  switch i32 %c, label %range [
    i32 65, label %case.element0
    i32 66, label %case.element1
    i32 67, label %case.element1
  ]

afterloop:                                        ; preds = %case_end
  ret i64 0

range:                                            ; preds = %loop
  br label %else

case.element0:                                    ; preds = %loop
  call void @Out_String([0 x i32]* @STRING_0)
  call void @Out_Ln()
  br label %case_end

case.element1:                                    ; preds = %loop, %loop
  call void @Out_String([0 x i32]* @STRING_1)
  call void @Out_Ln()
  br label %case_end

else:                                             ; preds = %range
  call void @Out_String([0 x i32]* @STRING_2)
  call void @Out_Ln()
  br label %case_end

case_end:                                         ; preds = %else, %case.element1, %case.element0
  %1 = load i64, i64* %i
  %nextvar = add i64 %1, 1
  store i64 %nextvar, i64* %i
  %loopcond = icmp sle i64 %nextvar, 4
  br i1 %loopcond, label %loop, label %afterloop
}
