; ModuleID = 'case2'
source_filename = "case2"

@case2_i = internal global i64 0
@STRING_0 = private global [0 x i32] [i32 79, i32 110, i32 101, i32 0]
@STRING_1 = private global [0 x i32] [i32 84, i32 119, i32 111, i32 0]
@STRING_2 = private global [0 x i32] [i32 77, i32 111, i32 114, i32 101, i32 0]

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define i64 @output() {
entry:
  %i = alloca i64
  store i64 1, i64* %i
  br label %loop

loop:                                             ; preds = %case_end, %entry
  %i1 = load i64, i64* %i
  switch i64 %i1, label %case_end [
    i64 1, label %case.element0
    i64 2, label %case.element02
    i64 3, label %case.element03
  ]

afterloop:                                        ; preds = %case_end
  ret i64 0

case.element0:                                    ; preds = %loop
  call void @Out_String([0 x i32]* @STRING_0)
  call void @Out_Ln()
  br label %case_end

case.element02:                                   ; preds = %loop
  call void @Out_String([0 x i32]* @STRING_1)
  call void @Out_Ln()
  br label %case_end

case.element03:                                   ; preds = %loop
  call void @Out_String([0 x i32]* @STRING_2)
  call void @Out_Ln()
  br label %case_end

case_end:                                         ; preds = %case.element03, %case.element02, %case.element0, %loop
  %0 = load i64, i64* %i
  %nextvar = add i64 %0, 1
  store i64 %nextvar, i64* %i
  %loopcond = icmp sle i64 %nextvar, 4
  br i1 %loopcond, label %loop, label %afterloop
}
