; ModuleID = 'char3'
source_filename = "char3"

@char3_x = internal global [3 x i32] zeroinitializer

define i64 @output() {
entry:
  store i32 65, i32* getelementptr inbounds ([3 x i32], [3 x i32]* @char3_x, i64 0, i64 0)
  %x = load [3 x i32], [3 x i32]* @char3_x
  %idx = load i32, i32* getelementptr inbounds ([3 x i32], [3 x i32]* @char3_x, i64 0, i64 0)
  %0 = zext i32 %idx to i64
  ret i64 %0
}
