; ModuleID = 'char5'
source_filename = "char5"

@char5_x = internal global i32 0

define i64 @output() {
entry:
  store i32 97, i32* @char5_x
  %x = load i32, i32* @char5_x
  %0 = icmp eq i32 %x, 97
  br i1 %0, label %then, label %ifcont

then:                                             ; preds = %entry
  %x1 = load i32, i32* @char5_x
  %1 = zext i32 %x1 to i64
  ret i64 %1

ifcont:                                           ; preds = %entry
  ret i64 0
}
