; ModuleID = 'e07'
source_filename = "e07"

@e07_x = internal global i64 0
@e07_i = internal global i64 0

define internal i64 @e07_f() {
entry:
  ret i64 9
}

define i64 @output() {
entry:
  store i64 0, i64* @e07_x
  store i64 0, i64* @e07_i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %x = load i64, i64* @e07_x
  %i = load i64, i64* @e07_i
  %addtmp = add i64 %x, %i
  store i64 %addtmp, i64* @e07_x
  %index = load i64, i64* @e07_i
  %nextvar = add i64 %index, 2
  store i64 %nextvar, i64* @e07_i
  %0 = call i64 @e07_f()
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, %0
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond1 = icmp sge i64 %nextvar, %0
  br i1 %loopcond1, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  %x2 = load i64, i64* @e07_x
  ret i64 %x2
}
