; ModuleID = 'e08'
source_filename = "e08"

@e08_x = internal global i64 0

declare void @WriteInt(i64)

declare void @WriteBoolean(i1)

declare void @WriteLn()

define i64 @output() {
entry:
  store i64 0, i64* @e08_x
  br label %begin

begin:                                            ; preds = %entry
  %x = load i64, i64* @e08_x
  %addtmp = add i64 %x, 1
  store i64 %addtmp, i64* @e08_x
  %x1 = load i64, i64* @e08_x
  %addtmp2 = add i64 %x1, 1
  store i64 %addtmp2, i64* @e08_x
  %x3 = load i64, i64* @e08_x
  %addtmp4 = add i64 %x3, 1
  store i64 %addtmp4, i64* @e08_x
  br label %end

end:                                              ; preds = %begin
  %x5 = load i64, i64* @e08_x
  ret i64 %x5
}
