; ModuleID = 'e13'
source_filename = "e13"

@e13_x = internal global i64 0

declare void @Out_Ln()

declare void @Out_Int(i64)

define i64 @output() {
entry:
  br label %loop

loop:                                             ; preds = %ifcont, %entry
  %x = load i64, i64* @e13_x
  %addtmp = add i64 %x, 1
  store i64 %addtmp, i64* @e13_x
  %x1 = load i64, i64* @e13_x
  call void @Out_Int(i64 %x1)
  call void @Out_Ln()
  %x2 = load i64, i64* @e13_x
  %0 = icmp ne i64 %x2, 10
  br i1 %0, label %then, label %else

then:                                             ; preds = %loop
  %x3 = load i64, i64* @e13_x
  store i64 %x3, i64* @e13_x
  br label %ifcont

else:                                             ; preds = %loop
  br label %end

ifcont:                                           ; preds = %then
  br label %loop

end:                                              ; preds = %else
  ret i64 0
}
