; ModuleID = 'inc2'
source_filename = "inc2"

@inc2_x = internal global i64 0

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @output() {
entry:
  store i64 0, i64* @inc2_x
  %0 = load i64, i64* @inc2_x
  %inc = add i64 %0, 1
  store i64 %inc, i64* @inc2_x
  %1 = load i64, i64* @inc2_x
  %inc1 = add i64 %1, 3
  store i64 %inc1, i64* @inc2_x
  %x = load i64, i64* @inc2_x
  %2 = load i64, i64* @inc2_x
  %inc2 = add i64 %2, %x
  store i64 %inc2, i64* @inc2_x
  %x3 = load i64, i64* @inc2_x
  call void @Out_Int(i64 %x3, i64 0)
  call void @Out_Ln()
  %3 = load i64, i64* @inc2_x
  %dec = sub i64 %3, 1
  store i64 %dec, i64* @inc2_x
  %4 = load i64, i64* @inc2_x
  %dec4 = sub i64 %4, 3
  store i64 %dec4, i64* @inc2_x
  %x5 = load i64, i64* @inc2_x
  %5 = load i64, i64* @inc2_x
  %dec6 = sub i64 %5, %x5
  store i64 %dec6, i64* @inc2_x
  %x7 = load i64, i64* @inc2_x
  call void @Out_Int(i64 %x7, i64 0)
  call void @Out_Ln()
  ret i64 0
}
