; ModuleID = 'long'
source_filename = "long"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

declare void @Out_Real(double, i64)

define i64 @output() {
entry:
  call void @Out_Int(i64 -17, i64 0)
  call void @Out_Ln()
  call void @Out_Real(double 3.100000e+00, i64 0)
  call void @Out_Ln()
  call void @Out_Ln()
  call void @Out_Int(i64 -17, i64 0)
  call void @Out_Ln()
  call void @Out_Real(double 3.100000e+00, i64 0)
  call void @Out_Ln()
  ret i64 0
}
