; ModuleID = 'max'
source_filename = "max"

@max_x = internal global i64 0
@max_b = internal global i1 false

declare void @Out_Bool(i1)

declare void @Out_Char(i32)

declare void @Out_Int(i64)

declare void @Out_Ln()

define i64 @output() {
entry:
  store i64 9223372036854775807, i64* @max_x
  %x = load i64, i64* @max_x
  call void @Out_Int(i64 %x)
  call void @Out_Ln()
  store i1 false, i1* @max_b
  %b = load i1, i1* @max_b
  call void @Out_Bool(i1 %b)
  call void @Out_Ln()
  call void @Out_Bool(i1 true)
  call void @Out_Char(i32 32)
  call void @Out_Bool(i1 false)
  call void @Out_Ln()
  call void @Out_Int(i64 9223372036854775807)
  call void @Out_Char(i32 32)
  call void @Out_Int(i64 -9223372036854775808)
  call void @Out_Ln()
  ret i64 0
}
