; ModuleID = 'odd'
source_filename = "odd"

@odd_i = internal global i64 0

declare i1 @ODD(i64)

declare void @Out_Ln()

declare void @Out_Bool(i1)

define i64 @output() {
entry:
  store i64 0, i64* @odd_i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %i = load i64, i64* @odd_i
  %0 = call i1 @ODD(i64 %i)
  call void @Out_Bool(i1 %0)
  call void @Out_Ln()
  %index = load i64, i64* @odd_i
  %nextvar = add i64 %index, 1
  store i64 %nextvar, i64* @odd_i
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 7
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond1 = icmp sge i64 %nextvar, 7
  br i1 %loopcond1, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  ret i64 0
}
