; ModuleID = 'pointer04'
source_filename = "pointer04"

@pointer04_x = internal global i64* null
@STRING_0 = private global [0 x i32] [i32 69, i32 113, i32 117, i32 97, i32 108, i32 115, i32 32, i32 78, i32 73, i32 76, i32 32, i32 0]
@STRING_1 = private global [0 x i32] [i32 78, i32 111, i32 116, i32 32, i32 69, i32 113, i32 117, i32 97, i32 108, i32 115, i32 32, i32 78, i32 73, i32 76, i32 32, i32 0]

declare void @Out_Ln()

declare void @Out_Bool(i1)

declare void @Out_String([0 x i32]*)

define i64 @output() {
entry:
  call void @Out_String([0 x i32]* @STRING_0)
  %x = load i64*, i64** @pointer04_x
  %0 = icmp eq i64* %x, null
  call void @Out_Bool(i1 %0)
  call void @Out_Ln()
  call void @Out_String([0 x i32]* @STRING_1)
  %x1 = load i64*, i64** @pointer04_x
  %1 = icmp ne i64* %x1, null
  call void @Out_Bool(i1 %1)
  call void @Out_Ln()
  %x2 = load i64*, i64** @pointer04_x
  %2 = icmp eq i64* %x2, null
  %3 = zext i1 %2 to i64
  ret i64 %3
}
