; ModuleID = 'pointer03'
source_filename = "pointer03"

%List = type { i64 }

@pointer03_start = internal global %List* null

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @output() {
entry:
  store void* null, %List** @pointer03_start
  %0 = call i64 @NEW_ptr(%List** @pointer03_start, i64 16)
  %1 = load %List*, %List** @pointer03_start
  %idx = getelementptr %List, %List* %1, i64 0, i32 0
  store i64 5, i64* %idx
  %start = load %List*, %List** @pointer03_start
  %2 = load %List*, %List** @pointer03_start
  %idx1 = getelementptr %List, %List* %2, i64 0, i32 0
  %idx2 = load i64, i64* %idx1
  call void @Out_Int(i64 %idx2, i64 0)
  call void @Out_Ln()
  ret i64 0
}

declare i64 @NEW_ptr(%List**, i64)
