; ModuleID = 'real02'
source_filename = "real02"

@real02_pi = internal constant double 0x400921FB5A7ED197
@real02_x = internal global double 0.000000e+00

declare void @Out_Ln()

declare void @Out_Real(double)

define i64 @output() {
entry:
  %pi = load double, double* @real02_pi
  %subtmp = fsub double %pi, 1.000000e+00
  store double %subtmp, double* @real02_x
  %x = load double, double* @real02_x
  call void @Out_Real(double %x)
  call void @Out_Ln()
  %pi1 = load double, double* @real02_pi
  %addtmp = fadd double %pi1, 1.000000e+00
  store double %addtmp, double* @real02_x
  %x2 = load double, double* @real02_x
  call void @Out_Real(double %x2)
  call void @Out_Ln()
  %pi3 = load double, double* @real02_pi
  %pi4 = load double, double* @real02_pi
  %multmp = fmul double %pi3, %pi4
  store double %multmp, double* @real02_x
  %x5 = load double, double* @real02_x
  call void @Out_Real(double %x5)
  call void @Out_Ln()
  %pi6 = load double, double* @real02_pi
  %divtmp = fdiv double %pi6, 2.000000e+00
  store double %divtmp, double* @real02_x
  %x7 = load double, double* @real02_x
  call void @Out_Real(double %x7)
  call void @Out_Ln()
  %pi8 = load double, double* @real02_pi
  %multmp9 = fmul double %pi8, 0.000000e+00
  store double %multmp9, double* @real02_x
  %x10 = load double, double* @real02_x
  call void @Out_Real(double %x10)
  call void @Out_Ln()
  %pi11 = load double, double* @real02_pi
  %divtmp12 = fdiv double %pi11, 0.000000e+00
  store double %divtmp12, double* @real02_x
  %x13 = load double, double* @real02_x
  call void @Out_Real(double %x13)
  call void @Out_Ln()
  ret i64 0
}
