; ModuleID = 'stdlib01'
source_filename = "stdlib01"

@stdlib01_x = internal constant i64 12

declare void @Out_Ln()

declare void @Out_Int(i64)

declare void @Out_Bool(i1)

declare void @Out_Open()

declare void @Out_Flush()

declare void @Out_Hex(i64)

define i64 @output() {
entry:
  call void @Out_Open()
  %x = load i64, i64* @stdlib01_x
  call void @Out_Int(i64 %x)
  call void @Out_Ln()
  call void @Out_Int(i64 3405691582)
  call void @Out_Ln()
  call void @Out_Hex(i64 3405691582)
  call void @Out_Ln()
  call void @Out_Bool(i1 true)
  call void @Out_Ln()
  call void @Out_Flush()
  ret i64 0
}
