; ModuleID = 'stdlib03'
source_filename = "stdlib03"

@stdlib03_a = internal constant [0 x i32]* @STRING_0
@STRING_0 = private global [0 x i32] [i32 72, i32 101, i32 108, i32 108, i32 111, i32 0]
@stdlib03_b = internal constant [0 x i32]* @STRING_1
@STRING_1 = private global [0 x i32] [i32 32, i32 87, i32 111, i32 114, i32 108, i32 100, i32 0]
@stdlib03_c = internal global [0 x i32]* null
@STRING_2 = private global [0 x i32] [i32 32, i32 45, i32 62, i32 32, i32 0]
@STRING_3 = private global [0 x i32] [i32 97, i32 0]
@STRING_4 = private global [0 x i32] [i32 98, i32 0]

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

declare void @Out_Char(i32)

declare void @Out_String([0 x i32]*)

declare [0 x i32]* @Strings_AppendChar(i32, [0 x i32]*)

declare [0 x i32]* @Strings_Concat([0 x i32]*, [0 x i32]*)

declare i64 @Strings_Compare([0 x i32]*, [0 x i32]*)

declare [0 x i32]* @Strings_ConcatChar([0 x i32]*, i32)

define internal void @stdlib03_print([0 x i32]* %s) {
entry:
  %s1 = alloca [0 x i32]*
  store [0 x i32]* %s, [0 x i32]** %s1
  %s2 = load [0 x i32]*, [0 x i32]** %s1
  call void @Out_String([0 x i32]* %s2)
  call void @Out_Char(i32 32)
  %s3 = load [0 x i32]*, [0 x i32]** %s1
  %0 = call i64 @Strings_Length([0 x i32]* %s3)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret void
}

declare i64 @Strings_Length([0 x i32]*)

define internal void @stdlib03_printCompare([0 x i32]* %s1, [0 x i32]* %s2) {
entry:
  %s22 = alloca [0 x i32]*
  %s11 = alloca [0 x i32]*
  store [0 x i32]* %s1, [0 x i32]** %s11
  store [0 x i32]* %s2, [0 x i32]** %s22
  %s13 = load [0 x i32]*, [0 x i32]** %s11
  call void @Out_String([0 x i32]* %s13)
  call void @Out_Char(i32 32)
  %s24 = load [0 x i32]*, [0 x i32]** %s22
  call void @Out_String([0 x i32]* %s24)
  call void @Out_String([0 x i32]* @STRING_2)
  %s15 = load [0 x i32]*, [0 x i32]** %s11
  %s26 = load [0 x i32]*, [0 x i32]** %s22
  %0 = call i64 @Strings_Compare([0 x i32]* %s15, [0 x i32]* %s26)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  %a = load [0 x i32]*, [0 x i32]** @stdlib03_a
  %b = load [0 x i32]*, [0 x i32]** @stdlib03_b
  %0 = call [0 x i32]* @Strings_Concat([0 x i32]* %a, [0 x i32]* %b)
  store [0 x i32]* %0, [0 x i32]** @stdlib03_c
  %c = load [0 x i32]*, [0 x i32]** @stdlib03_c
  call void @stdlib03_print([0 x i32]* %c)
  %c1 = load [0 x i32]*, [0 x i32]** @stdlib03_c
  %1 = call [0 x i32]* @Strings_ConcatChar([0 x i32]* %c1, i32 33)
  store [0 x i32]* %1, [0 x i32]** @stdlib03_c
  %c2 = load [0 x i32]*, [0 x i32]** @stdlib03_c
  call void @stdlib03_print([0 x i32]* %c2)
  %c3 = load [0 x i32]*, [0 x i32]** @stdlib03_c
  %2 = call [0 x i32]* @Strings_AppendChar(i32 33, [0 x i32]* %c3)
  store [0 x i32]* %2, [0 x i32]** @stdlib03_c
  %c4 = load [0 x i32]*, [0 x i32]** @stdlib03_c
  call void @stdlib03_print([0 x i32]* %c4)
  call void @Out_Ln()
  call void @stdlib03_printCompare([0 x i32]* @STRING_3, [0 x i32]* @STRING_3)
  call void @stdlib03_printCompare([0 x i32]* @STRING_3, [0 x i32]* @STRING_4)
  call void @stdlib03_printCompare([0 x i32]* @STRING_4, [0 x i32]* @STRING_3)
  ret i64 0
}
