; ModuleID = 'string8'
source_filename = "string8"

@string8_x = internal global [0 x i32]* null
@string8_y = internal global [0 x i32]* null
@STRING_0 = private global [0 x i32] [i32 72, i32 101, i32 108, i32 108, i32 111, i32 32, i32 116, i32 104, i32 101, i32 114, i32 101, i32 33, i32 0]
@STRING_1 = private global [0 x i32] [i32 79, i32 114, i32 105, i32 103, i32 110, i32 97, i32 108, i32 58, i32 0]

declare void @COPY([0 x i32]*, [0 x i32]*)

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define i64 @output() {
entry:
  store [0 x i32]* @STRING_0, [0 x i32]** @string8_x
  %x = load [0 x i32]*, [0 x i32]** @string8_x
  call void @COPY([0 x i32]* %x, [0 x i32]** @string8_y)
  %y = load [0 x i32]*, [0 x i32]** @string8_y
  call void @Out_String([0 x i32]* %y)
  call void @Out_Ln()
  call void @Out_String([0 x i32]* @STRING_1)
  call void @Out_Ln()
  %x1 = load [0 x i32]*, [0 x i32]** @string8_x
  call void @Out_String([0 x i32]* %x1)
  call void @Out_Ln()
  ret i64 0
}
