; ModuleID = 'string7'
source_filename = "string7"

@string7_x = internal global [0 x i32]* null

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define i64 @output() {
entry:
  %0 = call i64 @NEW_String([0 x i32]** @string7_x, i64 28)
  %1 = load [0 x i32]*, [0 x i32]** @string7_x
  %idx = getelementptr [0 x i32], [0 x i32]* %1, i64 0, i64 0
  store i32 72, i32* %idx
  %2 = load [0 x i32]*, [0 x i32]** @string7_x
  %idx1 = getelementptr [0 x i32], [0 x i32]* %2, i64 0, i64 1
  store i32 101, i32* %idx1
  %3 = load [0 x i32]*, [0 x i32]** @string7_x
  %idx2 = getelementptr [0 x i32], [0 x i32]* %3, i64 0, i64 2
  store i32 108, i32* %idx2
  %4 = load [0 x i32]*, [0 x i32]** @string7_x
  %idx3 = getelementptr [0 x i32], [0 x i32]* %4, i64 0, i64 3
  store i32 108, i32* %idx3
  %5 = load [0 x i32]*, [0 x i32]** @string7_x
  %idx4 = getelementptr [0 x i32], [0 x i32]* %5, i64 0, i64 4
  store i32 111, i32* %idx4
  %6 = load [0 x i32]*, [0 x i32]** @string7_x
  %idx5 = getelementptr [0 x i32], [0 x i32]* %6, i64 0, i64 5
  store i32 33, i32* %idx5
  %x = load [0 x i32]*, [0 x i32]** @string7_x
  call void @Out_String([0 x i32]* %x)
  call void @Out_Ln()
  ret i64 0
}

declare i64 @NEW_String([0 x i32]**, i64)
