; ModuleID = 'string10'
source_filename = "string10"

@string10_a = internal constant [0 x i32]* bitcast ([7 x i32]* @STRING_0 to [0 x i32]*)
@STRING_0 = private global [7 x i32] [i32 97, i32 108, i32 112, i32 104, i32 97, i32 32, i32 0]
@string10_b = internal constant [0 x i32]* bitcast ([6 x i32]* @STRING_1 to [0 x i32]*)
@STRING_1 = private global [6 x i32] [i32 98, i32 101, i32 116, i32 97, i32 32, i32 0]
@string10_cc = internal constant [0 x i32]* bitcast ([7 x i32]* @STRING_2 to [0 x i32]*)
@STRING_2 = private global [7 x i32] [i32 103, i32 97, i32 109, i32 109, i32 97, i32 32, i32 0]
@string10_c = internal global [0 x i32]* null
@string10_d = internal global [0 x i32]* null
@string10_e = internal global i32 0

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

declare void @Out_Char(i32)

declare void @Out_String([0 x i32]*)

define internal void @string10_print([0 x i32]* %s) {
entry:
  %s1 = alloca [0 x i32]*
  store [0 x i32]* %s, [0 x i32]** %s1
  %s2 = load [0 x i32]*, [0 x i32]** %s1
  call void @Out_String([0 x i32]* %s2)
  call void @Out_Char(i32 32)
  %s3 = load [0 x i32]*, [0 x i32]** %s1
  %0 = call i64 @Strings_Length([0 x i32]* %s3)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret void
}

declare i64 @Strings_Length([0 x i32]*)

define i64 @output() {
entry:
  %a = load [0 x i32]*, [0 x i32]** @string10_a
  call void @string10_print([0 x i32]* %a)
  %b = load [0 x i32]*, [0 x i32]** @string10_b
  call void @string10_print([0 x i32]* %b)
  %a1 = load [0 x i32]*, [0 x i32]** @string10_a
  %b2 = load [0 x i32]*, [0 x i32]** @string10_b
  %0 = call [0 x i32]* @Strings_Concat([0 x i32]* %a1, [0 x i32]* %b2)
  store [0 x i32]* %0, [0 x i32]** @string10_c
  %c = load [0 x i32]*, [0 x i32]** @string10_c
  call void @string10_print([0 x i32]* %c)
  %a3 = load [0 x i32]*, [0 x i32]** @string10_a
  call void @string10_print([0 x i32]* %a3)
  %b4 = load [0 x i32]*, [0 x i32]** @string10_b
  call void @string10_print([0 x i32]* %b4)
  %a5 = load [0 x i32]*, [0 x i32]** @string10_a
  %b6 = load [0 x i32]*, [0 x i32]** @string10_b
  %1 = call [0 x i32]* @Strings_Concat([0 x i32]* %a5, [0 x i32]* %b6)
  %cc = load [0 x i32]*, [0 x i32]** @string10_cc
  %2 = call [0 x i32]* @Strings_Concat([0 x i32]* %1, [0 x i32]* %cc)
  store [0 x i32]* %2, [0 x i32]** @string10_d
  %d = load [0 x i32]*, [0 x i32]** @string10_d
  call void @string10_print([0 x i32]* %d)
  %d7 = load [0 x i32]*, [0 x i32]** @string10_d
  %cc8 = load [0 x i32]*, [0 x i32]** @string10_cc
  %3 = call [0 x i32]* @Strings_Concat([0 x i32]* %d7, [0 x i32]* %cc8)
  store [0 x i32]* %3, [0 x i32]** @string10_d
  %d9 = load [0 x i32]*, [0 x i32]** @string10_d
  call void @string10_print([0 x i32]* %d9)
  store i32 65, i32* @string10_e
  %a10 = load [0 x i32]*, [0 x i32]** @string10_a
  %e = load i32, i32* @string10_e
  %4 = call [0 x i32]* @Strings_ConcatChar([0 x i32]* %a10, i32 %e)
  store [0 x i32]* %4, [0 x i32]** @string10_d
  %d11 = load [0 x i32]*, [0 x i32]** @string10_d
  call void @string10_print([0 x i32]* %d11)
  store i32 48, i32* @string10_e
  %e12 = load i32, i32* @string10_e
  %a13 = load [0 x i32]*, [0 x i32]** @string10_a
  %5 = call [0 x i32]* @Strings_AppendChar(i32 %e12, [0 x i32]* %a13)
  store [0 x i32]* %5, [0 x i32]** @string10_d
  %d14 = load [0 x i32]*, [0 x i32]** @string10_d
  call void @string10_print([0 x i32]* %d14)
  ret i64 0
}

declare [0 x i32]* @Strings_Concat([0 x i32]*, [0 x i32]*)

declare [0 x i32]* @Strings_ConcatChar([0 x i32]*, i32)

declare [0 x i32]* @Strings_AppendChar(i32, [0 x i32]*)
