; ModuleID = 'string5'
source_filename = "string5"

@string5_x = internal global [0 x i32]* null
@STRING_0 = private global [0 x i32] [i32 72, i32 101, i32 108, i32 108, i32 111, i32 0]

declare void @Out_Ln()

declare void @Out_Char(i32)

define i64 @output() {
entry:
  %i = alloca i64
  store [0 x i32]* @STRING_0, [0 x i32]** @string5_x
  store i64 0, i64* %i
  br label %loop

loop:                                             ; preds = %loop, %entry
  %x = load [0 x i32]*, [0 x i32]** @string5_x
  %i1 = load i64, i64* %i
  %0 = load [0 x i32]*, [0 x i32]** @string5_x
  %idx = getelementptr [0 x i32], [0 x i32]* %0, i64 0, i64 %i1
  %idx2 = load i32, i32* %idx
  call void @Out_Char(i32 %idx2)
  call void @Out_Char(i32 32)
  %1 = load i64, i64* %i
  %nextvar = add i64 %1, 1
  store i64 %nextvar, i64* %i
  %x3 = load [0 x i32]*, [0 x i32]** @string5_x
  %2 = call i64 @Strings_Length([0 x i32]* %x3)
  %subtmp = sub i64 %2, 1
  %loopcond = icmp sle i64 %nextvar, %subtmp
  br i1 %loopcond, label %loop, label %afterloop

afterloop:                                        ; preds = %loop
  call void @Out_Ln()
  ret i64 0
}

declare i64 @Strings_Length([0 x i32]*)
