; ModuleID = 'string6'
source_filename = "string6"

@string6_x = internal global [0 x i32]* null
@STRING_0 = private global [0 x i32] [i32 72, i32 101, i32 108, i32 108, i32 111, i32 0]

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define i64 @output() {
entry:
  store [0 x i32]* @STRING_0, [0 x i32]** @string6_x
  %x = load [0 x i32]*, [0 x i32]** @string6_x
  call void @Out_String([0 x i32]* %x)
  call void @Out_Ln()
  %0 = load [0 x i32]*, [0 x i32]** @string6_x
  %idx = getelementptr [0 x i32], [0 x i32]* %0, i64 0, i64 0
  store i32 66, i32* %idx
  %1 = load [0 x i32]*, [0 x i32]** @string6_x
  %idx1 = getelementptr [0 x i32], [0 x i32]* %1, i64 0, i64 1
  store i32 105, i32* %idx1
  %x2 = load [0 x i32]*, [0 x i32]** @string6_x
  call void @Out_String([0 x i32]* %x2)
  call void @Out_Ln()
  %x3 = load [0 x i32]*, [0 x i32]** @string6_x
  %2 = load [0 x i32]*, [0 x i32]** @string6_x
  %idx4 = getelementptr [0 x i32], [0 x i32]* %2, i64 0, i64 0
  %idx5 = load i32, i32* %idx4
  %3 = zext i32 %idx5 to i64
  ret i64 %3
}
