; ModuleID = 'string2'
source_filename = "string2"

@string2_x = internal global i32* null
@string2_y = internal global i32* null
@STRING_0 = constant [5 x i32] [i32 72, i32 101, i32 108, i32 108, i32 111, i32 0]

declare void @Out_Ln()

declare void @Out_String(i32*)

define internal i32* @string2_identity(i32* %x) {
entry:
  %x1 = alloca i32*
  store i32* %x, i32** %x1
  %x2 = load i32*, i32** %x1
  ret i32* %x2
}

define i64 @output() {
entry:
  store [5 x i32]* @STRING_0, i32** @string2_x
  %x = load i32*, i32** @string2_x
  %0 = call i32* @string2_identity(i32* %x)
  store i32* %0, i32** @string2_y
  %y = load i32*, i32** @string2_y
  call void @Out_String(i32* %y)
  call void @Out_Ln()
  ret i64 0
}
