; ModuleID = 'Assert3'
source_filename = "Assert3"

@Assert3_x = internal global i64 0

define i64 @output() {
entry:
  store i64 123, i64* @Assert3_x
  %x = load i64, i64* @Assert3_x
  br i1 false, label %assert, label %merge

assert:                                           ; preds = %entry
  %0 = call i64 @HALT(i64 %x)
  br label %merge

merge:                                            ; preds = %assert, %entry
  ret i64 0
}

declare i64 @HALT(i64)
