; ModuleID = 'Assign19'
source_filename = "Assign19"

%0 = type { i64, i64 }

@Assign19_r1 = internal global %0 zeroinitializer
@Assign19_r2 = internal global %0 zeroinitializer
@Assign19_r4 = internal global %0 zeroinitializer

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal void @Assign19_P1() {
entry:
  %r1 = load %0, %0* @Assign19_r1
  %idx = load i64, i64* getelementptr inbounds (%0, %0* @Assign19_r1, i64 0, i32 0)
  call void @Out_Int(i64 %idx, i64 10)
  %r11 = load %0, %0* @Assign19_r1
  %idx2 = load i64, i64* getelementptr inbounds (%0, %0* @Assign19_r1, i64 0, i32 1)
  call void @Out_Int(i64 %idx2, i64 10)
  call void @Out_Ln()
  ret void
}

define internal void @Assign19_P2() {
entry:
  %r2 = load %0, %0* @Assign19_r2
  %idx = load i64, i64* getelementptr inbounds (%0, %0* @Assign19_r2, i64 0, i32 0)
  call void @Out_Int(i64 %idx, i64 10)
  %r21 = load %0, %0* @Assign19_r2
  %idx2 = load i64, i64* getelementptr inbounds (%0, %0* @Assign19_r2, i64 0, i32 1)
  call void @Out_Int(i64 %idx2, i64 10)
  call void @Out_Ln()
  ret void
}

define internal void @Assign19_P4() {
entry:
  %r4 = load %0, %0* @Assign19_r4
  %idx = load i64, i64* getelementptr inbounds (%0, %0* @Assign19_r4, i64 0, i32 0)
  call void @Out_Int(i64 %idx, i64 10)
  %r41 = load %0, %0* @Assign19_r4
  %idx2 = load i64, i64* getelementptr inbounds (%0, %0* @Assign19_r4, i64 0, i32 1)
  call void @Out_Int(i64 %idx2, i64 10)
  call void @Out_Ln()
  ret void
}

define void @Assign19_Test() {
entry:
  store i64 1, i64* getelementptr inbounds (%0, %0* @Assign19_r1, i64 0, i32 0)
  call void @Assign19_P1()
  store i64 258, i64* getelementptr inbounds (%0, %0* @Assign19_r2, i64 0, i32 0)
  call void @Assign19_P2()
  store i64 67371521, i64* getelementptr inbounds (%0, %0* @Assign19_r4, i64 0, i32 0)
  call void @Assign19_P4()
  ret void
}

define i64 @output() {
entry:
  store i64 0, i64* getelementptr inbounds (%0, %0* @Assign19_r1, i64 0, i32 0)
  store i64 -1, i64* getelementptr inbounds (%0, %0* @Assign19_r1, i64 0, i32 1)
  store i64 0, i64* getelementptr inbounds (%0, %0* @Assign19_r2, i64 0, i32 0)
  store i64 -1, i64* getelementptr inbounds (%0, %0* @Assign19_r2, i64 0, i32 1)
  store i64 0, i64* getelementptr inbounds (%0, %0* @Assign19_r4, i64 0, i32 0)
  store i64 -1, i64* getelementptr inbounds (%0, %0* @Assign19_r4, i64 0, i32 1)
  call void @Assign19_Test()
  ret i64 0
}
