; ModuleID = 'C1'
source_filename = "C1"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @C1_Sub(i64 %a1, i64 %b2) {
entry:
  %b = alloca i64
  %a = alloca i64
  store i64 %a1, i64* %a
  store i64 %b2, i64* %b
  %a3 = load i64, i64* %a
  %b4 = load i64, i64* %b
  %subtmp = sub i64 %a3, %b4
  ret i64 %subtmp
}

define i64 @C1_f(i64 %a1, i64 %b2) {
entry:
  %b = alloca i64
  %a = alloca i64
  store i64 %a1, i64* %a
  store i64 %b2, i64* %b
  %a3 = load i64, i64* %a
  %b4 = load i64, i64* %b
  %0 = call i64 @C1_Sub(i64 %a3, i64 %b4)
  ret i64 %0
}

define i64 @output() {
entry:
  %0 = call i64 @C1_f(i64 5, i64 2)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
