; ModuleID = 'C1'
source_filename = "C1"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @C1_Sub(i64 %a, i64 %b) {
entry:
  %b2 = alloca i64
  %a1 = alloca i64
  store i64 %a, i64* %a1
  store i64 %b, i64* %b2
  %a3 = load i64, i64* %a1
  %b4 = load i64, i64* %b2
  %subtmp = sub i64 %a3, %b4
  ret i64 %subtmp
}

define i64 @C1_f(i64 %a, i64 %b) {
entry:
  %b2 = alloca i64
  %a1 = alloca i64
  store i64 %a, i64* %a1
  store i64 %b, i64* %b2
  %a3 = load i64, i64* %a1
  %b4 = load i64, i64* %b2
  %0 = call i64 @C1_Sub(i64 %a3, i64 %b4)
  ret i64 %0
}

define i64 @output() {
entry:
  %0 = call i64 @C1_f(i64 5, i64 2)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
