; ModuleID = 'Case9'
source_filename = "Case9"

define internal void @Case9_P(i64 %i) {
entry:
  %i1 = alloca i64
  store i64 %i, i64* %i1
  %i2 = load i64, i64* %i1
  switch i64 %i2, label %case.range [
    i64 1, label %case.element0
  ]

case.range:                                       ; preds = %entry
  br label %case.range0

case.range0:                                      ; preds = %case.range
  %0 = icmp sle i64 0, %i2
  %1 = icmp sle i64 %i2, 2
  %2 = and i1 %0, %1
  br i1 %2, label %case.element1, label %case.end

case.element0:                                    ; preds = %entry
  br label %case.end

case.element1:                                    ; preds = %case.range0
  br label %case.end

case.end:                                         ; preds = %case.element1, %case.element0, %case.range0
  ret void
}

define i64 @output() {
entry:
  call void @Case9_P(i64 2)
  ret i64 0
}
