; ModuleID = 'Case5'
source_filename = "Case5"

define internal void @Case5_P(i64 %i) {
entry:
  %i1 = alloca i64
  store i64 %i, i64* %i1
  %i2 = load i64, i64* %i1
  switch i64 %i2, label %case.range [
    i64 128, label %case.element0
  ]

case.range:                                       ; preds = %entry
  br label %case.end

case.element0:                                    ; preds = %entry
  br label %case.end

case.end:                                         ; preds = %case.element0, %case.range
  ret void
}

define i64 @output() {
entry:
  call void @Case5_P(i64 2)
  ret i64 0
}
