; ModuleID = 'Case4'
source_filename = "Case4"

define internal void @Case4_P(i64 %i1, i64 %j2) {
entry:
  %j = alloca i64
  %i = alloca i64
  store i64 %i1, i64* %i
  store i64 %j2, i64* %j
  %i3 = load i64, i64* %i
  switch i64 %i3, label %case.range [
  ]

case.range:                                       ; preds = %entry
  br label %case.range0

case.range0:                                      ; preds = %case.range
  %0 = icmp sle i64 1, %i3
  %j4 = load i64, i64* %j
  %1 = icmp sle i64 %i3, %j4
  %2 = and i1 %0, %1
  br i1 %2, label %case.element0, label %case.end

case.element0:                                    ; preds = %case.range0
  br label %case.end

case.end:                                         ; preds = %case.element0, %case.range0
  ret void
}

define i64 @output() {
entry:
  call void @Case4_P(i64 1, i64 3)
  ret i64 0
}
