; ModuleID = 'Case7'
source_filename = "Case7"

define internal void @Case7_P(i64 %i1) {
entry:
  %i = alloca i64
  store i64 %i1, i64* %i
  %i2 = load i64, i64* %i
  switch i64 %i2, label %case.range [
    i64 1, label %case.element0
    i64 1, label %case.element1
  ]

case.range:                                       ; preds = %entry
  br label %case.end

case.element0:                                    ; preds = %entry
  br label %case.end

case.element1:                                    ; preds = %entry
  br label %case.end

case.end:                                         ; preds = %case.element1, %case.element0, %case.range
  ret void
}

define i64 @output() {
entry:
  call void @Case7_P(i64 2)
  ret i64 0
}
