; ModuleID = 'ConstFold7'
source_filename = "ConstFold7"

@ConstFold7_a = internal global [16 x i32] zeroinitializer

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define void @ConstFold7_Test() {
entry:
  %a = load [16 x i32], [16 x i32]* @ConstFold7_a
  call void @Out_Int(i64 16, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @ConstFold7_Test()
  ret i64 0
}
