; ModuleID = 'Const1'
source_filename = "Const1"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @Const1_F() {
entry:
  %x = alloca i64
  store i64 0, i64* %x
  br i1 false, label %then, label %else

then:                                             ; preds = %entry
  store i64 3, i64* %x
  br label %ifcont

else:                                             ; preds = %entry
  store i64 7, i64* %x
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %x1 = load i64, i64* %x
  %addtmp = add i64 %x1, 5
  ret i64 %addtmp
}

define void @Const1_Test() {
entry:
  %0 = call i64 @Const1_F()
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @Const1_Test()
  ret i64 0
}
