; ModuleID = 'Cse3'
source_filename = "Cse3"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @Cse3_F(i64 %x) {
entry:
  %x1 = alloca i64
  store i64 %x, i64* %x1
  %x2 = load i64, i64* %x1
  %x3 = load i64, i64* %x1
  %addtmp = add i64 %x2, %x3
  %x4 = load i64, i64* %x1
  %x5 = load i64, i64* %x1
  %addtmp6 = add i64 %x4, %x5
  %addtmp7 = add i64 %addtmp, %addtmp6
  ret i64 %addtmp7
}

define void @Cse3_Test() {
entry:
  %0 = call i64 @Cse3_F(i64 3)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @Cse3_Test()
  ret i64 0
}
