; ModuleID = 'Dead1'
source_filename = "Dead1"

define internal void @Dead1_P() {
entry:
  %i1 = alloca i64
  %j = alloca i64
  %i = alloca i64
  store i64 0, i64* %i
  store i64 0, i64* %j
  store i64 123, i64* %j
  store i64 0, i64* %i1
  br label %loop

loop:                                             ; preds = %loop, %entry
  %0 = load i64, i64* %j
  %inc = add i64 %0, 1
  store i64 %inc, i64* %j
  %1 = load i64, i64* %i1
  %nextvar = add i64 %1, 1
  store i64 %nextvar, i64* %i1
  %loopcond = icmp sle i64 %nextvar, 9
  br i1 %loopcond, label %loop, label %afterloop

afterloop:                                        ; preds = %loop
  ret void
}

define i64 @output() {
entry:
  call void @Dead1_P()
  ret i64 0
}
