; ModuleID = 'Div3'
source_filename = "Div3"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal void @Div3_Div(i64 %i) {
entry:
  %i1 = alloca i64
  store i64 %i, i64* %i1
  %i2 = load i64, i64* %i1
  %divtmp = sdiv i64 %i2, 2
  call void @Out_Int(i64 %divtmp, i64 3)
  call void @Out_Ln()
  ret void
}

define void @Div3_Test() {
entry:
  call void @Div3_Div(i64 2)
  call void @Div3_Div(i64 -2)
  ret void
}

define i64 @output() {
entry:
  call void @Div3_Test()
  ret i64 0
}
