; ModuleID = 'For10'
source_filename = "For10"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define void @For10_Test() {
entry:
  %x = alloca i64
  store i64 0, i64* %x
  store i64 8, i64* %x
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %x1 = load i64, i64* %x
  call void @Out_Int(i64 %x1, i64 0)
  call void @Out_Ln()
  %index = load i64, i64* %x
  %nextvar = add i64 %index, -2
  store i64 %nextvar, i64* %x
  br i1 false, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 1
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond2 = icmp sge i64 %nextvar, 1
  br i1 %loopcond2, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  ret void
}

define i64 @output() {
entry:
  call void @For10_Test()
  ret i64 0
}
