; ModuleID = 'For11'
source_filename = "For11"

define void @For11_Test() {
entry:
  %j = alloca i64
  %i = alloca i64
  %c = alloca i64
  store i64 0, i64* %c
  store i64 0, i64* %i
  store i64 0, i64* %j
  store i64 0, i64* %c
  store i64 0, i64* %i
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  store i64 0, i64* %j
  br label %loop1

forpos:                                           ; preds = %afterloop4
  %loopcond9 = icmp sle i64 %nextvar8, 1
  br i1 %loopcond9, label %loop, label %afterloop

forneg:                                           ; preds = %afterloop4
  %loopcond10 = icmp sge i64 %nextvar8, 1
  br i1 %loopcond10, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  %c11 = load i64, i64* %c
  %0 = icmp eq i64 %c11, 3
  %1 = xor i1 %0, true
  br i1 %1, label %assert, label %merge

loop1:                                            ; preds = %forneg3, %forpos2, %loop
  %2 = load i64, i64* %c
  %inc = add i64 %2, 1
  store i64 %inc, i64* %c
  %index = load i64, i64* %j
  %nextvar = add i64 %index, 1
  store i64 %nextvar, i64* %j
  %i5 = load i64, i64* %i
  br i1 true, label %forpos2, label %forneg3

forpos2:                                          ; preds = %loop1
  %loopcond = icmp sle i64 %nextvar, %i5
  br i1 %loopcond, label %loop1, label %afterloop4

forneg3:                                          ; preds = %loop1
  %loopcond6 = icmp sge i64 %nextvar, %i5
  br i1 %loopcond6, label %loop1, label %afterloop4

afterloop4:                                       ; preds = %forneg3, %forpos2
  %index7 = load i64, i64* %i
  %nextvar8 = add i64 %index7, 1
  store i64 %nextvar8, i64* %i
  br i1 true, label %forpos, label %forneg

assert:                                           ; preds = %afterloop
  %3 = call i64 @HALT(i64 1)
  br label %merge

merge:                                            ; preds = %assert, %afterloop
  ret void
}

declare i64 @HALT(i64)

define i64 @output() {
entry:
  call void @For11_Test()
  ret i64 0
}
