; ModuleID = 'For11'
source_filename = "For11"

define void @For11_Test() {
entry:
  %j4 = alloca i64
  %i1 = alloca i64
  %j = alloca i64
  %i = alloca i64
  %c = alloca i64
  store i64 0, i64* %c
  store i64 0, i64* %i
  store i64 0, i64* %j
  store i64 0, i64* %c
  store i64 0, i64* %i1
  br label %loop

loop:                                             ; preds = %afterloop3, %entry
  store i64 0, i64* %j4
  br label %loop2

afterloop:                                        ; preds = %afterloop3
  %c8 = load i64, i64* %c
  %0 = icmp eq i64 %c8, 3
  %1 = xor i1 %0, true
  br i1 %1, label %assert, label %merge

loop2:                                            ; preds = %loop2, %loop
  %2 = load i64, i64* %c
  %inc = add i64 %2, 1
  store i64 %inc, i64* %c
  %3 = load i64, i64* %j4
  %nextvar = add i64 %3, 1
  store i64 %nextvar, i64* %j4
  %i5 = load i64, i64* %i1
  %loopcond = icmp sle i64 %nextvar, %i5
  br i1 %loopcond, label %loop2, label %afterloop3

afterloop3:                                       ; preds = %loop2
  %4 = load i64, i64* %i1
  %nextvar6 = add i64 %4, 1
  store i64 %nextvar6, i64* %i1
  %loopcond7 = icmp sle i64 %nextvar6, 1
  br i1 %loopcond7, label %loop, label %afterloop

assert:                                           ; preds = %afterloop
  %5 = call i64 @HALT(i64 1)
  br label %merge

merge:                                            ; preds = %assert, %afterloop
  ret void
}

declare i64 @HALT(i64)

define i64 @output() {
entry:
  call void @For11_Test()
  ret i64 0
}
