; ModuleID = 'For5'
source_filename = "For5"

define void @For5_Test() {
entry:
  %x = alloca i64
  store i64 0, i64* %x
  store i64 127, i64* %x
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %index = load i64, i64* %x
  %nextvar = add i64 %index, 1
  store i64 %nextvar, i64* %x
  br i1 true, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 128
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond1 = icmp sge i64 %nextvar, 128
  br i1 %loopcond1, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  ret void
}

define i64 @output() {
entry:
  call void @For5_Test()
  ret i64 0
}
