; ModuleID = 'For7'
source_filename = "For7"

define void @For7_Test() {
entry:
  %y = alloca i64
  %x = alloca i64
  store i64 0, i64* %x
  store i64 0, i64* %y
  store i64 1, i64* %y
  store i64 0, i64* %x
  br label %loop

loop:                                             ; preds = %forneg, %forpos, %entry
  %y1 = load i64, i64* %y
  %index = load i64, i64* %x
  %nextvar = add i64 %index, %y1
  store i64 %nextvar, i64* %x
  %0 = icmp sge i64 %y1, 0
  br i1 %0, label %forpos, label %forneg

forpos:                                           ; preds = %loop
  %loopcond = icmp sle i64 %nextvar, 127
  br i1 %loopcond, label %loop, label %afterloop

forneg:                                           ; preds = %loop
  %loopcond2 = icmp sge i64 %nextvar, 127
  br i1 %loopcond2, label %loop, label %afterloop

afterloop:                                        ; preds = %forneg, %forpos
  ret void
}

define i64 @output() {
entry:
  call void @For7_Test()
  ret i64 0
}
