; ModuleID = 'For7'
source_filename = "For7"

define void @For7_Test() {
entry:
  %x1 = alloca i64
  %y = alloca i64
  %x = alloca i64
  store i64 0, i64* %x
  store i64 0, i64* %y
  store i64 1, i64* %y
  store i64 0, i64* %x1
  br label %loop

loop:                                             ; preds = %loop, %entry
  %y2 = load i64, i64* %y
  %0 = load i64, i64* %x1
  %nextvar = add i64 %0, %y2
  store i64 %nextvar, i64* %x1
  %loopcond = icmp sle i64 %nextvar, 127
  br i1 %loopcond, label %loop, label %afterloop

afterloop:                                        ; preds = %loop
  ret void
}

define i64 @output() {
entry:
  call void @For7_Test()
  ret i64 0
}
