; ModuleID = 'HOTFunction4'
source_filename = "HOTFunction4"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @HOTFunction4_Select(i1 %b) {
entry:
  %b1 = alloca i1
  store i1 %b, i1* %b1
  %b2 = load i1, i1* %b1
  br i1 %b2, label %then, label %else

then:                                             ; preds = %entry
  ret i64 1

else:                                             ; preds = %entry
  ret i64 0

ifcont:                                           ; No predecessors!
  ret i64 0
}

define void @HOTFunction4_Test() {
entry:
  %0 = call i64 @HOTFunction4_Select(i1 false)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  %1 = call i64 @HOTFunction4_Select(i1 true)
  call void @Out_Int(i64 %1, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @HOTFunction4_Test()
  ret i64 0
}
