; ModuleID = 'HOTFunction5'
source_filename = "HOTFunction5"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @HOTFunction5_Inc(i64 %n1) {
entry:
  %n = alloca i64
  store i64 %n1, i64* %n
  %n2 = load i64, i64* %n
  %addtmp = add i64 %n2, 1
  ret i64 %addtmp
}

define void @HOTFunction5_Test() {
entry:
  %0 = call i64 @HOTFunction5_Inc(i64 -1)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  %1 = call i64 @HOTFunction5_Inc(i64 0)
  call void @Out_Int(i64 %1, i64 0)
  call void @Out_Ln()
  %2 = call i64 @HOTFunction5_Inc(i64 1)
  call void @Out_Int(i64 %2, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @HOTFunction5_Test()
  ret i64 0
}
