; ModuleID = 'HOTFunction3'
source_filename = "HOTFunction3"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @HOTFunction3_Identity(i64 %n) {
entry:
  %x = alloca i64
  %n1 = alloca i64
  store i64 %n, i64* %n1
  store i64 0, i64* %x
  %n2 = load i64, i64* %n1
  store i64 %n2, i64* %x
  %x3 = load i64, i64* %x
  ret i64 %x3
}

define void @HOTFunction3_Test() {
entry:
  %0 = call i64 @HOTFunction3_Identity(i64 1)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  %1 = call i64 @HOTFunction3_Identity(i64 2)
  call void @Out_Int(i64 %1, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @HOTFunction3_Test()
  ret i64 0
}
