; ModuleID = 'HOTFunction1'
source_filename = "HOTFunction1"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @HOTFunction1_OneTwoThree() {
entry:
  ret i64 123
}

define void @HOTFunction1_Test() {
entry:
  call void @Out_Int(i64 123, i64 0)
  call void @Out_Ln()
  %0 = call i64 @HOTFunction1_OneTwoThree()
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @HOTFunction1_Test()
  ret i64 0
}
