; ModuleID = 'HOTIf1'
source_filename = "HOTIf1"

@STRING_0 = private global [5 x i32] [i32 84, i32 82, i32 85, i32 69, i32 0]
@STRING_1 = private global [6 x i32] [i32 70, i32 65, i32 76, i32 83, i32 69, i32 0]

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define internal void @HOTIf1_If(i1 %b) {
entry:
  %x = alloca i64
  %b1 = alloca i1
  store i1 %b, i1* %b1
  store i64 0, i64* %x
  %b2 = load i1, i1* %b1
  br i1 %b2, label %then, label %else

then:                                             ; preds = %entry
  call void @Out_String([0 x i32]* bitcast ([5 x i32]* @STRING_0 to [0 x i32]*))
  br label %ifcont

else:                                             ; preds = %entry
  call void @Out_String([0 x i32]* bitcast ([6 x i32]* @STRING_1 to [0 x i32]*))
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  call void @Out_Ln()
  ret void
}

define void @HOTIf1_Test() {
entry:
  call void @HOTIf1_If(i1 true)
  call void @HOTIf1_If(i1 false)
  ret void
}

define i64 @output() {
entry:
  call void @HOTIf1_Test()
  ret i64 0
}
