; ModuleID = 'HOTLoop9'
source_filename = "HOTLoop9"

define void @HOTLoop9_Test() {
entry:
  br label %while

while:                                            ; preds = %entry
  br i1 true, label %loop, label %end

loop:                                             ; preds = %while
  br label %end

end:                                              ; preds = %loop, %while
  ret void
}

define i64 @output() {
entry:
  call void @HOTLoop9_Test()
  ret i64 0
}
