; ModuleID = 'HOTVarPar1'
source_filename = "HOTVarPar1"

@HOTVarPar1_a = internal global i64 0

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal void @HOTVarPar1_Set(i64* %x, i64 %val) {
entry:
  %val2 = alloca i64
  %x1 = alloca i64*
  store i64* %x, i64** %x1
  store i64 %val, i64* %val2
  %val3 = load i64, i64* %val2
  %x4 = load i64*, i64** %x1
  %x5 = load i64*, i64** %x1
  store i64 %val3, i64* %x5
  ret void
}

define void @HOTVarPar1_Test() {
entry:
  call void @HOTVarPar1_Set(i64* @HOTVarPar1_a, i64 2)
  %a = load i64, i64* @HOTVarPar1_a
  call void @Out_Int(i64 %a, i64 0)
  call void @Out_Ln()
  call void @HOTVarPar1_Set(i64* @HOTVarPar1_a, i64 3)
  %a1 = load i64, i64* @HOTVarPar1_a
  call void @Out_Int(i64 %a1, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @HOTVarPar1_Test()
  ret i64 0
}
