; ModuleID = 'Len4'
source_filename = "Len4"

@STRING_0 = private global [4 x i32] [i32 97, i32 98, i32 99, i32 0]

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define void @Len4_Test() {
entry:
  %0 = call i64 @Strings_Length([0 x i32]* bitcast ([4 x i32]* @STRING_0 to [0 x i32]*))
  call void @Out_Int(i64 %0, i64 2)
  call void @Out_Ln()
  ret void
}

declare i64 @Strings_Length([0 x i32]*)

define i64 @output() {
entry:
  call void @Len4_Test()
  ret i64 0
}
