; ModuleID = 'LongReal1'
source_filename = "LongReal1"

declare void @Out_Ln()

declare void @Out_LongReal(double, i64)

define internal void @LongReal1_Print(double %x) {
entry:
  %x1 = alloca double
  store double %x, double* %x1
  %x2 = load double, double* %x1
  call void @Out_LongReal(double %x2, i64 3)
  call void @Out_Ln()
  ret void
}

define void @LongReal1_Test() {
entry:
  call void @LongReal1_Print(double 1.000000e+00)
  call void @LongReal1_Print(double 2.000000e+00)
  call void @LongReal1_Print(double -2.500000e-02)
  ret void
}

define i64 @output() {
entry:
  call void @LongReal1_Test()
  ret i64 0
}
