; ModuleID = 'LongReal2'
source_filename = "LongReal2"

declare void @Out_Ln()

declare void @Out_LongReal(double, i64)

define internal void @LongReal2_Print(double %x) {
entry:
  %x1 = alloca double
  store double %x, double* %x1
  %x2 = load double, double* %x1
  call void @Out_LongReal(double %x2, i64 3)
  call void @Out_Ln()
  ret void
}

define internal void @LongReal2_Print2(double %x) {
entry:
  %x1 = alloca double
  store double %x, double* %x1
  %x2 = load double, double* %x1
  call void @LongReal2_Print(double %x2)
  ret void
}

define void @LongReal2_Test() {
entry:
  call void @LongReal2_Print2(double 1.000000e+00)
  call void @LongReal2_Print2(double 2.000000e+00)
  call void @LongReal2_Print2(double -2.500000e-02)
  ret void
}

define i64 @output() {
entry:
  call void @LongReal2_Test()
  ret i64 0
}
