; ModuleID = 'LongReal3'
source_filename = "LongReal3"

declare void @Out_Ln()

declare void @Out_LongReal(double, i64)

define internal void @LongReal3_Print(double %x) {
entry:
  %x1 = alloca double
  store double %x, double* %x1
  %x2 = load double, double* %x1
  call void @Out_LongReal(double %x2, i64 3)
  call void @Out_Ln()
  ret void
}

define internal double @LongReal3_f() {
entry:
  ret double 1.000000e+00
}

define internal double @LongReal3_g() {
entry:
  ret double 2.000000e+00
}

define internal double @LongReal3_h() {
entry:
  ret double -2.500000e-02
}

define void @LongReal3_Test() {
entry:
  %0 = call double @LongReal3_f()
  call void @LongReal3_Print(double %0)
  %1 = call double @LongReal3_g()
  call void @LongReal3_Print(double %1)
  %2 = call double @LongReal3_h()
  call void @LongReal3_Print(double %2)
  ret void
}

define i64 @output() {
entry:
  call void @LongReal3_Test()
  ret i64 0
}
