; ModuleID = 'NestedProc1'
source_filename = "NestedProc1"

@STRING_0 = private global [0 x i32] [i32 72, i32 101, i32 108, i32 108, i32 111, i32 32, i32 87, i32 111, i32 114, i32 108, i32 100, i32 0]

declare void @Out_Ln()

declare void @Out_String([0 x i32]*)

define void @NestedProc1_Test() {
entry:
  call void @NestedProc1_Test_Inner()
  ret void
}

define internal void @NestedProc1_Test_Inner() {
entry:
  call void @Out_String([0 x i32]* @STRING_0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @NestedProc1_Test()
  ret i64 0
}
