; ModuleID = 'NestedProc3'
source_filename = "NestedProc3"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define void @NestedProc3_Test() {
entry:
  %x = alloca i64
  store i64 0, i64* %x
  store i64 -1, i64* %x
  %x1 = load i64, i64* %x
  call void @NestedProc3_Test_Inner(i64 %x1)
  %x2 = load i64, i64* %x
  call void @Out_Int(i64 %x2, i64 0)
  call void @Out_Ln()
  ret void
}

define internal void @NestedProc3_Test_Inner(i64 %x1) {
entry:
  %x = alloca i64
  store i64 %x1, i64* %x
  store i64 123, i64* %x
  ret void
}

define i64 @output() {
entry:
  call void @NestedProc3_Test()
  ret i64 0
}
