; ModuleID = 'NestedProc2'
source_filename = "NestedProc2"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define void @NestedProc2_Test() {
entry:
  %closure_struct = alloca [1 x i64*]
  %x = alloca i64
  store i64 0, i64* %x
  store i64 -1, i64* %x
  %cls = getelementptr [1 x i64*], [1 x i64*]* %closure_struct, i64 0, i64 0
  store i64* %x, i64** %cls
  call void @NestedProc2_Test_Inner([1 x i64*]* nest %closure_struct)
  %x1 = load i64, i64* %x
  call void @Out_Int(i64 %x1, i64 0)
  call void @Out_Ln()
  ret void
}

define internal void @NestedProc2_Test_Inner([1 x i64*]* nest %0) {
entry:
  %x = getelementptr [1 x i64*], [1 x i64*]* %0, i64 0, i64 0
  %x1 = load i64*, i64** %x
  store i64 123, i64* %x1
  ret void
}

define i64 @output() {
entry:
  call void @NestedProc2_Test()
  ret i64 0
}
