; ModuleID = 'Odd1'
source_filename = "Odd1"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

declare void @Out_Bool(i1)

define internal void @Odd1_Odd(i64 %x1, i1 %odd2) {
entry:
  %odd = alloca i1
  %x = alloca i64
  store i64 %x1, i64* %x
  store i1 %odd2, i1* %odd
  %x3 = load i64, i64* %x
  call void @Out_Int(i64 %x3, i64 4)
  %odd4 = load i1, i1* %odd
  call void @Out_Bool(i1 %odd4)
  %odd5 = load i1, i1* %odd
  call void @Out_Bool(i1 %odd5)
  call void @Out_Ln()
  ret void
}

define void @Odd1_Test() {
entry:
  call void @Odd1_Odd(i64 65, i1 true)
  call void @Odd1_Odd(i64 96, i1 false)
  call void @Odd1_Odd(i64 -1, i1 true)
  call void @Odd1_Odd(i64 0, i1 false)
  ret void
}

define i64 @output() {
entry:
  call void @Odd1_Test()
  ret i64 0
}
