; ModuleID = 'OpArray9'
source_filename = "OpArray9"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal i64 @OpArray9_One() {
entry:
  ret i64 1
}

define void @OpArray9_Test() {
entry:
  %a = alloca [3 x i64]
  store [3 x i64] zeroinitializer, [3 x i64]* %a
  %idx = getelementptr [3 x i64], [3 x i64]* %a, i64 0, i64 0
  store i64 0, i64* %idx
  %idx1 = getelementptr [3 x i64], [3 x i64]* %a, i64 0, i64 1
  store i64 1, i64* %idx1
  %idx2 = getelementptr [3 x i64], [3 x i64]* %a, i64 0, i64 2
  store i64 2, i64* %idx2
  %a3 = load [3 x i64], [3 x i64]* %a
  %0 = call i64 @OpArray9_One()
  %idx4 = getelementptr [3 x i64], [3 x i64]* %a, i64 0, i64 %0
  %idx5 = load i64, i64* %idx4
  call void @Out_Int(i64 %idx5, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @OpArray9_Test()
  ret i64 0
}
