; ModuleID = 'OpExprCompat12'
source_filename = "OpExprCompat12"

define void @OpExprCompat12_Test() {
entry:
  %l = alloca double
  %s = alloca double
  store double 0.000000e+00, double* %s
  store double 0.000000e+00, double* %l
  %s1 = load double, double* %s
  %l2 = load double, double* %l
  %addtmp = fadd double %s1, %l2
  store double %addtmp, double* %s
  ret void
}

define i64 @output() {
entry:
  call void @OpExprCompat12_Test()
  ret i64 0
}
