; ModuleID = 'OpExprCompat14'
source_filename = "OpExprCompat14"

define void @OpExprCompat14_Test() {
entry:
  %k = alloca double
  %j = alloca double
  %i = alloca double
  store double 0.000000e+00, double* %i
  store double 0.000000e+00, double* %j
  store double 0.000000e+00, double* %k
  %j1 = load double, double* %j
  %k2 = load double, double* %k
  %divtmp = fdiv double %j1, %k2
  store double %divtmp, double* %i
  ret void
}

define i64 @output() {
entry:
  call void @OpExprCompat14_Test()
  ret i64 0
}
