; ModuleID = 'Proc13'
source_filename = "Proc13"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal void @Proc13_P(i64 %y1) {
entry:
  %y = alloca i64
  store i64 %y1, i64* %y
  store i64 99, i64* %y
  ret void
}

define void @Proc13_Test() {
entry:
  %x = alloca i64
  store i64 0, i64* %x
  store i64 12, i64* %x
  %x1 = load i64, i64* %x
  call void @Out_Int(i64 %x1, i64 0)
  call void @Out_Ln()
  %x2 = load i64, i64* %x
  call void @Proc13_P(i64 %x2)
  %x3 = load i64, i64* %x
  call void @Out_Int(i64 %x3, i64 0)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @Proc13_Test()
  ret i64 0
}
