; ModuleID = 'Real3'
source_filename = "Real3"

declare void @Out_Ln()

declare void @Out_Real(double, i64)

define internal void @Real3_Print(double %x1) {
entry:
  %x = alloca double
  store double %x1, double* %x
  %x2 = load double, double* %x
  call void @Out_Real(double %x2, i64 3)
  call void @Out_Ln()
  ret void
}

define internal double @Real3_f() {
entry:
  ret double 1.000000e+00
}

define internal double @Real3_g() {
entry:
  ret double 2.000000e+00
}

define internal double @Real3_h() {
entry:
  ret double -2.500000e-02
}

define void @Real3_Test() {
entry:
  %0 = call double @Real3_f()
  call void @Real3_Print(double %0)
  %1 = call double @Real3_g()
  call void @Real3_Print(double %1)
  %2 = call double @Real3_h()
  call void @Real3_Print(double %2)
  ret void
}

define i64 @output() {
entry:
  call void @Real3_Test()
  ret i64 0
}
