; ModuleID = 'Real1'
source_filename = "Real1"

declare void @Out_Ln()

declare void @Out_Real(double, i64)

define internal void @Real1_Print(double %x1) {
entry:
  %x = alloca double
  store double %x1, double* %x
  %x2 = load double, double* %x
  call void @Out_Real(double %x2, i64 3)
  call void @Out_Ln()
  ret void
}

define void @Real1_Test() {
entry:
  call void @Real1_Print(double 1.000000e+00)
  call void @Real1_Print(double 2.000000e+00)
  call void @Real1_Print(double -2.500000e-02)
  ret void
}

define i64 @output() {
entry:
  call void @Real1_Test()
  ret i64 0
}
