; ModuleID = 'Record6'
source_filename = "Record6"

%R = type { i64, i64 }

@Record6_r = internal global %R zeroinitializer

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal void @Record6_Set(%R %r1, i64 %a2, i64 %b3) {
entry:
  %b = alloca i64
  %a = alloca i64
  %r = alloca %R
  store %R %r1, %R* %r
  store i64 %a2, i64* %a
  store i64 %b3, i64* %b
  %a4 = load i64, i64* %a
  %idx = getelementptr %R, %R* %r, i64 0, i32 0
  store i64 %a4, i64* %idx
  %b5 = load i64, i64* %b
  %idx6 = getelementptr %R, %R* %r, i64 0, i32 1
  store i64 %b5, i64* %idx6
  ret void
}

define void @Record6_Test() {
entry:
  store i64 1, i64* getelementptr inbounds (%R, %R* @Record6_r, i64 0, i32 0)
  store i64 2, i64* getelementptr inbounds (%R, %R* @Record6_r, i64 0, i32 1)
  %r = load %R, %R* @Record6_r
  %idx = load i64, i64* getelementptr inbounds (%R, %R* @Record6_r, i64 0, i32 0)
  call void @Out_Int(i64 %idx, i64 2)
  %r1 = load %R, %R* @Record6_r
  %idx2 = load i64, i64* getelementptr inbounds (%R, %R* @Record6_r, i64 0, i32 1)
  call void @Out_Int(i64 %idx2, i64 2)
  call void @Out_Ln()
  %r3 = load %R, %R* @Record6_r
  call void @Record6_Set(%R %r3, i64 3, i64 4)
  %r4 = load %R, %R* @Record6_r
  %idx5 = load i64, i64* getelementptr inbounds (%R, %R* @Record6_r, i64 0, i32 0)
  call void @Out_Int(i64 %idx5, i64 2)
  %r6 = load %R, %R* @Record6_r
  %idx7 = load i64, i64* getelementptr inbounds (%R, %R* @Record6_r, i64 0, i32 1)
  call void @Out_Int(i64 %idx7, i64 2)
  call void @Out_Ln()
  ret void
}

define i64 @output() {
entry:
  call void @Record6_Test()
  ret i64 0
}
