; ModuleID = 'Short1'
source_filename = "Short1"

define void @Short1_Test() {
entry:
  %r32 = alloca double
  %r64 = alloca double
  %i32 = alloca i64
  %i16 = alloca i64
  %i8 = alloca i64
  store i64 0, i64* %i8
  store i64 0, i64* %i16
  store i64 0, i64* %i32
  store double 0.000000e+00, double* %r64
  store double 0.000000e+00, double* %r32
  store i64 1, i64* %i32
  %i321 = load i64, i64* %i32
  store i64 %i321, i64* %i16
  %i162 = load i64, i64* %i16
  store i64 %i162, i64* %i8
  store double 1.000000e+00, double* %r64
  %r643 = load double, double* %r64
  store double %r643, double* %r32
  store i64 0, i64* %i8
  ret void
}

define i64 @output() {
entry:
  call void @Short1_Test()
  ret i64 0
}
