; ModuleID = 'T2'
source_filename = "T2"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @T2_f(i64 %a1, i64 %b2) {
entry:
  %b = alloca i64
  %a = alloca i64
  store i64 %a1, i64* %a
  store i64 %b2, i64* %b
  %a3 = load i64, i64* %a
  %b4 = load i64, i64* %b
  %subtmp = sub i64 %a3, %b4
  ret i64 %subtmp
}

define i64 @output() {
entry:
  %0 = call i64 @T2_f(i64 7, i64 4)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
