; ModuleID = 'T4'
source_filename = "T4"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @T4_f(i1 %select1, i64 %a2, i64 %b3) {
entry:
  %x = alloca i64
  %b = alloca i64
  %a = alloca i64
  %select = alloca i1
  store i1 %select1, i1* %select
  store i64 %a2, i64* %a
  store i64 %b3, i64* %b
  store i64 0, i64* %x
  %select4 = load i1, i1* %select
  br i1 %select4, label %then, label %else

then:                                             ; preds = %entry
  %a5 = load i64, i64* %a
  %b6 = load i64, i64* %b
  %addtmp = add i64 %a5, %b6
  store i64 %addtmp, i64* %x
  br label %ifcont

else:                                             ; preds = %entry
  %a7 = load i64, i64* %a
  %b8 = load i64, i64* %b
  %subtmp = sub i64 %a7, %b8
  store i64 %subtmp, i64* %x
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %x9 = load i64, i64* %x
  ret i64 %x9
}

define i64 @output() {
entry:
  %0 = call i64 @T4_f(i1 true, i64 3, i64 17)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
