; ModuleID = 'T6'
source_filename = "T6"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @T6_f(i1 %a, i1 %b) {
entry:
  %b2 = alloca i1
  %a1 = alloca i1
  store i1 %a, i1* %a1
  store i1 %b, i1* %b2
  %a3 = load i1, i1* %a1
  br i1 %a3, label %and_next, label %and_end

and_next:                                         ; preds = %entry
  %b4 = load i1, i1* %b2
  br label %and_end

and_end:                                          ; preds = %and_next, %entry
  %and = phi i1 [ %a3, %entry ], [ %b4, %and_next ]
  br i1 %and, label %then, label %else

then:                                             ; preds = %and_end
  ret i64 9

else:                                             ; preds = %and_end
  ret i64 -9

ifcont:                                           ; No predecessors!
  ret i64 -9
}

define i64 @output() {
entry:
  %0 = call i64 @T6_f(i1 true, i1 true)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
