; ModuleID = 'T6a'
source_filename = "T6a"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @T6a_f(i1 %a1, i1 %b2, i1 %c3) {
entry:
  %c = alloca i1
  %b = alloca i1
  %a = alloca i1
  store i1 %a1, i1* %a
  store i1 %b2, i1* %b
  store i1 %c3, i1* %c
  %a4 = load i1, i1* %a
  br i1 %a4, label %and_next, label %and_end

and_next:                                         ; preds = %entry
  %b5 = load i1, i1* %b
  br label %and_end

and_end:                                          ; preds = %and_next, %entry
  %and = phi i1 [ %a4, %entry ], [ %b5, %and_next ]
  br i1 %and, label %and_next6, label %and_end8

and_next6:                                        ; preds = %and_end
  %c7 = load i1, i1* %c
  br label %and_end8

and_end8:                                         ; preds = %and_next6, %and_end
  %and9 = phi i1 [ %and, %and_end ], [ %c7, %and_next6 ]
  br i1 %and9, label %then, label %else

then:                                             ; preds = %and_end8
  ret i64 9

else:                                             ; preds = %and_end8
  ret i64 -9

ifcont:                                           ; No predecessors!
  ret i64 -9
}

define i64 @output() {
entry:
  %0 = call i64 @T6a_f(i1 true, i1 true, i1 true)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
