; ModuleID = 'T7a'
source_filename = "T7a"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @T7a_f(i1 %a1, i1 %b2, i1 %c3) {
entry:
  %c = alloca i1
  %b = alloca i1
  %a = alloca i1
  store i1 %a1, i1* %a
  store i1 %b2, i1* %b
  store i1 %c3, i1* %c
  %a4 = load i1, i1* %a
  br i1 %a4, label %or_end, label %or_next

or_next:                                          ; preds = %entry
  %b5 = load i1, i1* %b
  br label %or_end

or_end:                                           ; preds = %or_next, %entry
  %or = phi i1 [ %a4, %entry ], [ %b5, %or_next ]
  br i1 %or, label %or_end8, label %or_next6

or_next6:                                         ; preds = %or_end
  %c7 = load i1, i1* %c
  br label %or_end8

or_end8:                                          ; preds = %or_next6, %or_end
  %or9 = phi i1 [ %or, %or_end ], [ %c7, %or_next6 ]
  br i1 %or9, label %then, label %else

then:                                             ; preds = %or_end8
  ret i64 9

else:                                             ; preds = %or_end8
  ret i64 -9

ifcont:                                           ; No predecessors!
  ret i64 -9
}

define i64 @output() {
entry:
  %0 = call i64 @T7a_f(i1 false, i1 true, i1 true)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
