; ModuleID = 'T8b'
source_filename = "T8b"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @T8b_f(i1 %a, i1 %b, i1 %c) {
entry:
  %c3 = alloca i1
  %b2 = alloca i1
  %a1 = alloca i1
  store i1 %a, i1* %a1
  store i1 %b, i1* %b2
  store i1 %c, i1* %c3
  %a4 = load i1, i1* %a1
  br i1 %a4, label %and_next, label %and_end

and_next:                                         ; preds = %entry
  %b5 = load i1, i1* %b2
  br i1 %b5, label %or_end, label %or_next

or_next:                                          ; preds = %and_next
  %c6 = load i1, i1* %c3
  br label %or_end

or_end:                                           ; preds = %or_next, %and_next
  %or = phi i1 [ %b5, %and_next ], [ %c6, %or_next ]
  br label %and_end

and_end:                                          ; preds = %or_end, %entry
  %and = phi i1 [ %a4, %entry ], [ %or, %or_end ]
  br i1 %and, label %then, label %else

then:                                             ; preds = %and_end
  ret i64 9

else:                                             ; preds = %and_end
  ret i64 -9

ifcont:                                           ; No predecessors!
  ret i64 -9
}

define i64 @output() {
entry:
  %0 = call i64 @T8b_f(i1 false, i1 true, i1 true)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
