; ModuleID = 'Undef18'
source_filename = "Undef18"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @Undef18_P() {
entry:
  %x = alloca i64
  %y = alloca i64
  store i64 0, i64* %y
  store i64 0, i64* %x
  %0 = call i64 @Undef18_P_N(i64* %x)
  store i64 %0, i64* %y
  store i64 1, i64* %x
  %1 = call i64 @Undef18_P_N(i64* %x)
  ret i64 %1
}

define internal i64 @Undef18_P_N(i64* %z1) {
entry:
  %z = alloca i64*
  store i64* %z1, i64** %z
  %z2 = load i64*, i64** %z
  %z3 = load i64, i64* %z2
  ret i64 %z3
}

define i64 @output() {
entry:
  %0 = call i64 @Undef18_P()
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
