; ModuleID = 'Undef4'
source_filename = "Undef4"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @Undef4_P(i1 %b) {
entry:
  %x = alloca i64
  %b1 = alloca i1
  store i1 %b, i1* %b1
  store i64 0, i64* %x
  %b2 = load i1, i1* %b1
  br i1 %b2, label %then, label %else

then:                                             ; preds = %entry
  br label %ifcont

else:                                             ; preds = %entry
  store i64 1, i64* %x
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %x3 = load i64, i64* %x
  ret i64 %x3
}

define i64 @output() {
entry:
  %0 = call i64 @Undef4_P(i1 true)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
