; ModuleID = 'Undef2'
source_filename = "Undef2"

%R = type { i64, i64 }

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @Undef2_P() {
entry:
  %r = alloca %R
  store %R zeroinitializer, %R* %r
  %idx = getelementptr %R, %R* %r, i64 0, i32 0
  store i64 1, i64* %idx
  %r1 = load %R, %R* %r
  %idx2 = getelementptr %R, %R* %r, i64 0, i32 0
  %idx3 = load i64, i64* %idx2
  ret i64 %idx3
}

define i64 @output() {
entry:
  %0 = call i64 @Undef2_P()
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
