; ModuleID = 'Undef13'
source_filename = "Undef13"

declare void @Out_Ln()

declare void @Out_Bool(i1)

define i1 @Undef13_Fct(i1 %b1) {
entry:
  %b = alloca i1
  store i1 %b1, i1* %b
  %b2 = load i1, i1* %b
  br i1 %b2, label %then, label %ifcont

then:                                             ; preds = %entry
  ret i1 false

ifcont:                                           ; preds = %entry
  ret i1 false
}

define i64 @output() {
entry:
  %0 = call i1 @Undef13_Fct(i1 true)
  call void @Out_Bool(i1 %0)
  call void @Out_Ln()
  ret i64 0
}
