; ModuleID = 'Undef25'
source_filename = "Undef25"

%R = type { i64 }

define void @Undef25_P() {
entry:
  %r = alloca %R
  store %R zeroinitializer, %R* %r
  call void @Undef25_P_N(%R* %r)
  ret void
}

define internal void @Undef25_P_N(%R* %x1) {
entry:
  %x = alloca %R*
  store %R* %x1, %R** %x
  %x2 = load %R*, %R** %x
  %x3 = load %R*, %R** %x
  %x4 = load %R*, %R** %x
  %0 = load %R*, %R** %x
  %idx = getelementptr %R, %R* %0, i64 0, i32 0
  store i64 1, i64* %idx
  ret void
}

define i64 @output() {
entry:
  call void @Undef25_P()
  ret i64 0
}
