; ModuleID = 'Undef6'
source_filename = "Undef6"

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define i64 @Undef6_P(i1 %b1) {
entry:
  %x = alloca i64
  %b = alloca i1
  store i1 %b1, i1* %b
  store i64 0, i64* %x
  br label %loop

loop:                                             ; preds = %ifcont, %entry
  %b2 = load i1, i1* %b
  br i1 %b2, label %then, label %else

then:                                             ; preds = %loop
  store i64 1, i64* %x
  br label %end

else:                                             ; preds = %loop
  br label %end

ifcont:                                           ; No predecessors!
  br label %loop

end:                                              ; preds = %else, %then
  %x3 = load i64, i64* %x
  ret i64 %x3
}

define i64 @output() {
entry:
  %0 = call i64 @Undef6_P(i1 true)
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
