; ModuleID = 'Undef27'
source_filename = "Undef27"

declare void @HALT(i64)

declare void @Out_Ln()

declare void @Out_Int(i64, i64)

define internal void @Undef27_Q() {
entry:
  call void @HALT(i64 1)
  ret void
}

define i64 @Undef27_P() {
entry:
  call void @Undef27_Q()
  ret i64 1
}

define i64 @output() {
entry:
  %0 = call i64 @Undef27_P()
  call void @Out_Int(i64 %0, i64 0)
  call void @Out_Ln()
  ret i64 0
}
