name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.14

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: homebrew
      run: brew install bdw-gc graphviz doxygen
    - name: cmake
      run: mkdir build; cd build; cmake ..
    - name: make
      run: cd build; make -j 2
    - name: test
      run: AXLIB_PATH=`pwd`/lib ; export AXLIB_PATH ; cd build ; ctest -j 2
