name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.14

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: homebrew
      run: brew install bdw-gc
    - name: cmake
      run: mkdir build; cd build; cmake ..
    - name: make
      run: cd build; make
    - name: test
      run: cd build; ctest
